# -*- coding: utf-8 -*-
"""
Created on Mon Apr  1 12:13:06 2019

@author: mikedelong
"""

from json import load
from os.path import exists
from time import time

import matplotlib.pyplot as plt
from nltk import FreqDist
from nltk import word_tokenize
from nltk.tokenize import casual_tokenize
from nltk.tokenize import sent_tokenize
from tika import parser


def fix(arg):
    result = list()
    skip = False
    for item_index, item in enumerate(arg):
        if item.endswith('-'):
            out_item = item[:-1]
            result.append(out_item + arg[item_index + 1])
            skip = True
        else:
            if skip:
                skip = False
            else:
                result.append(item)
    return result


settings_file = 'first_cut.json'
if __name__ == '__main__':
    time_start = time()
    with open(settings_file, 'r') as settings_fp:
        settings = load(settings_fp)

    input_folder = settings['input_folder'] if \
        'input_folder' in settings.keys() else None
    if input_folder is not None:
        if not exists(input_folder):
            print('input data folder does not exist. Quitting.')
            quit(-1)
    else:
        print('input folder name is missing from settings. Quitting.')
        quit(-1)

    input_file = settings['input_file'] if 'input_file' in settings.keys() else None
    full_input_file = None
    if input_file is not None:
        full_input_file = input_folder + input_file if input_folder.endswith('/') else input_folder + '/' + input_file
    else:
        print('input file name is missing from settings. Quitting.')
        quit(-1)

    if not exists(full_input_file):
        print('input file {} is missing. Quitting.'.format(full_input_file))
        quit(-1)

    parsed = parser.from_file(full_input_file)

    print('our content is a string of length {}'.format(len(parsed['content'])))
    content = parsed['content']

    # todo fix quotes
    # todo put summary sentences back in order
    sentences = sent_tokenize(content, language='english')

    print('before we remove very short sentences we have {} sentences'.format(len(sentences)))
    sentences = [item for item in sentences if len(item) > 1]
    print('after we remove very short sentences we have {} sentences'.format(len(sentences)))

    fixes = {'suf-fering': 'suffering', 'includ-ing': 'including', 'diplo-macy': 'diplomacy',
             'investi-gation': 'investigation', 'polit-ical': 'political', 'dis-tinction': 'distinction',
             'terror-ists': 'terrorists', 'fel-low': 'fellow', 'com-pletion': 'completion', 'fam-ilies': 'families',
             'per-son': 'person', 'under-standing': 'understanding', 'determi-nation': 'determination',
             'rec-ommendations': 'recommendations', 'Vir-ginia': 'Virginia', 'com-puterized': 'computerized',
             'Passen-ger': 'Passenger', 'air-craft': 'aircraft', 'appar-ently': 'apparently',
             'con-trolled': 'controlled', 'per-form': 'perform',
             # '22-caliber': '22caliber',
             'suspi-cious': 'suspicious',
             'first-class': 'firstclass', 'air-line': 'airline', 'screen-ing': 'screening', 'Han-jour': 'Hanjour',
             'Admin-istration': 'Administration', 'qual-ity': 'quality', 'explo-sives': 'explosives',
             'check-points': 'checkpoints', 'any-thing': 'anything', 'plan-ning': 'planning',
             'transmis-sion': 'transmission', 'cock-pit': 'cockpit', 'real-izing': 'realizing', 'Car-olina': 'Carolina',
             'real-ized': 'realized', 'Amer-ican': 'American', 'trans-mission': 'transmission',
             'broad-cast': 'broadcast', 'East-erners': 'Easterners', 'every-body': 'everybody',
             '00.Cap-tain': '00. Captain',
             'pas-senger': 'passenger', 'eye-witness': 'eyewitness',
             'similari-ties': 'similarities', 'try-ing': 'trying', 'storm-ing': 'storming',
             'com-munication.The': 'communication. The',
             'stab-bings': 'stabbings', 'repeat-edly': 'repeatedly',
             'sec-ond': 'second', 'fur-ther': 'further', 'Gen-eral': 'General', 'con-trollers': 'controllers',
             'deter-mined': 'determined', 'Ser-vice': 'Service',
             'House.Amer-ican': 'House. American',
             # '330-degree': '330degree',
             'travel-ing': 'traveling', 'civil-ian': 'civilian', 'Cap-tain': 'Captain',
             'atten-dants': 'attendants', 'attack-ers': 'attackers', 'Hern-don': 'Herndon',
             'transcon-tinental': 'transcontinental', 'Cen-ter': 'Center', 'respon-sibility': 'responsibility',
             'air-lines': 'airlines', 'pro-ceeded': 'proceeded', 'Head-ing': 'Heading', 'strug-gle': 'struggle',
             'shout-ing': 'shouting', 'manip-ulated': 'manipulated', 'oper-ated': 'operated', 'min-utes': 'minutes',
             'Air-port': 'Airport', 'hijack-ers': 'hijackers', 'follow-ing': 'following', 'pas-sengers': 'passengers',
             'cer-tainly': 'certainly', 'Jar-rah': 'Jarrah', 'passen-gers': 'passengers', 'ask-ing': 'asking',
             'mem-bers': 'members', 'sus-tained': 'sustained', 'air-plane': 'airplane',
             'counter-attack': 'counterattack', 'Penn-sylvania': 'Pennsylvania', 'traf-fic': 'traffic',
             'work-ing': 'working', 'man-dated': 'mandated', 'deci-sions': 'decisions', 'Indi-anapolis': 'Indianapolis',
             'primar-ily': 'primarily', 'Con-trollers': 'Controllers', 'commer-cial': 'commercial',
             'estab-lished': 'established', 'mis-sion': 'mission', 'plan-ners': 'planners', 'proto-cols': 'protocols',
             'gov-ernment': 'government', 'pro-vide': 'provide', 'stan-dard': 'standard',
             'commu-nication': 'communication', 'spe-cific': 'specific', 'teleconfer-ence': 'teleconference',
             'alti-tude': 'altitude', 'com-mand.In': 'command.In', 'ini-tiative': 'initiative',
             # 'F-16s': 'F16s',
             # 'F-15': 'F15',
             'con-troller': 'controller', 'Air-lines': 'Airlines', 'stew-ardesses': 'stewardesses',
             'man-ager': 'manager', 'Com-mand': 'Command', 'Evi-dence': 'Evidence', 'pick-ing': 'picking',
             'com-ing': 'coming', 'termi-nated': 'terminated', 'deci-phered': 'deciphered', 'hold-ing': 'holding',
             'con-cerned': 'concerned', 'Lan-gley': 'Langley', 'turn-ing': 'turning', 'tar-gets': 'targets',
             'air-line.Again': 'airline.Again', 'electri-cal': 'electrical', 'infor-mation': 'information',
             'dis-cussion': 'discussion', 'facili-ties': 'facilities', 'headquar-ters': 'headquarters',
             'inves-tigate': 'investigate', 'cov-erage': 'coverage',
             'posi-tion.The': 'position. The',
             'south-west': 'southwest', 'look-ing': 'looking', 'nei-ther': 'neither', 'cen-ters': 'centers',
             'pri-mary': 'primary',
             # 'C-130H': 'C130H',
             # 'iden-“': 'iden“',
             'Wash-ington': 'Washington',
             'discov-ered': 'discovered', 'tar-get': 'target', 'Lang-ley': 'Langley', 'deter-mine': 'determine',
             'remain-ing': 'remaining', 'communi-cation': 'communication', 'inter-cept': 'intercept',
             'climb-ing': 'climbing', 'han-dled': 'handled', 'mili-tary': 'military', 'head-quarters': 'headquarters',
             'coun-terattack': 'counterattack', 'spec-ulating': 'speculating', 'Penta-gon': 'Pentagon',
             'pre-existing': 'preexisting', 'unpre-pared': 'unprepared', 'man-agers': 'managers',
             'recommend-ing': 'recommending', 'over-stated': 'overstated', 'informa-tion': 'information',
             'offi-cials': 'officials', 'state-ment': 'statement', 'inac-curate': 'inaccurate',
             'respond-ing': 'responding', 'oper-ations': 'operations', 'inci-dent.At': 'incident.At',
             'inci-dent': 'incident', 'acci-dent': 'accident', 'peri-odically': 'periodically',
             'remem-bered': 'remembered', 'frus-trated': 'frustrated', 'Sit-uation': 'Situation',
             'partici-pated': 'participated', 'person-nel': 'personnel',
             # 'pos-36': 'pos36',
             'break-fast': 'breakfast',
             'all-purpose': 'allpurpose', 'mil-itary': 'military', 'familiar-ity': 'familiarity',
             'command-ers': 'commanders', 'situa-tion': 'situation', 'Sec-retary': 'Secretary', 'Chair-man': 'Chairman',
             'pos-sible': 'possible', 'Mil-itary': 'Military', 'tele-conference': 'teleconference',
             'some-body': 'somebody', 'Pres-ident': 'President', 'offi-cer': 'officer', 'approach-ing': 'approaching',
             'begin-ning': 'beginning', 'imme-diate': 'immediate', 'televi-sion': 'television', 'advis-ing': 'advising',
             'Presi-dent': 'President', 'con-cluded': 'concluded', 'empha-sized': 'emphasized',
             'incom-plete': 'incomplete', 'get-ting': 'getting', 'track-ing': 'tracking',
             'conversa-tion': 'conversation', 'proba-bly': 'probably', 'two-minute': 'twominute',
             'confer-ence': 'conference', 'head-ing': 'heading', 'sen-ior': 'senior', 'cir-cling': 'circling',
             'combat-ant': 'combatant', 'author-ity': 'authority', 'con-firmed': 'confirmed', 'cen-ter': 'center',
             'trans-mitted': 'transmitted', 'instruc-tions': 'instructions', 'scram-bled': 'scrambled',
             'oper-ating': 'operating', 'reach-ing': 'reaching', 'Washing-ton': 'Washington',
             'authoriza-tion': 'authorization', 'shoot-down': 'shootdown', 'com-plex': 'complex',
             'home-land': 'homeland',
             # '40-year-old': '40year-old',
             'inter-pretation': 'interpretation',
             'mes-senger': 'messenger', 'Mus-lims': 'Muslims', 'retalia-tion': 'retaliation', 'Ara-bic': 'Arabic',
             'dis-grace': 'disgrace', 'contin-ues': 'continues', 'single-mindedness': 'singlemindedness',
             'indiscrimi-nate': 'indiscriminate', 'griev-ances': 'grievances', 'Ara-bia': 'Arabia', 'Mus-lim': 'Muslim',
             'major-ity': 'majority', 'cen-tury': 'century', 'them-selves': 'themselves', 'lead-ers': 'leaders',
             'mem-ber': 'member', 'Egypt-ian': 'Egyptian', 'West-ern': 'Western', 'rev-elations': 'revelations',
             'peo-ple': 'people', 'wor-thy': 'worthy', 'Pales-tine': 'Palestine', 'ques-tion': 'question',
             'aban-don': 'abandon', 'civ-ilization': 'civilization', 'artic-ulate': 'articulate', 'sec-ular': 'secular',
             'I.Western-educated': 'I. Westerneducated',
             'sur-vive': 'survive', 'ide-ologies': 'ideologies',
             'coun-tries': 'countries', 'poli-cies': 'policies', 'Embold-ened': 'Emboldened', 'schol-ars': 'scholars',
             'cre-ated': 'created', 'wide-spread': 'widespread', 'enor-mous': 'enormous', 'edu-cational': 'educational',
             'edu-cation': 'education', 'com-monly': 'commonly', 'dis-agree': 'disagree', 'what-ever': 'whatever',
             'bil-lion': 'billion', 'victori-ous': 'victorious', 'organi-zation': 'organization',
             'extrem-ists': 'extremists', 'coun-try': 'country', 'vol-unteers': 'volunteers',
             'gen-erously': 'generously', 'nongovern-mental': 'nongovernmental', 'Inter-Services': 'InterServices',
             'dis-tribute': 'distribute', 'com-mittee': 'committee', 'Coun-cil': 'Council', 'grow-ing': 'growing',
             'unchal-lenged': 'unchallenged', 'influ-ence': 'influence', 'organiza-tions': 'organizations',
             'distrib-uted': 'distributed', 'fol-lowers': 'followers',
             # '.-led': '.led',
             'num-ber': 'number',
             'oper-atives': 'operatives', 'com-pany': 'company',
             # 'Tuc-THE': 'TucTHE',
             'Philip-pines': 'Philippines',
             'enter-prise': 'enterprise', 'con-duit': 'conduit', 'con-federation': 'confederation', 'Jor-dan': 'Jordan',
             'connec-tions': 'connections', 'ter-rorist': 'terrorist', 'Philip-pine': 'Philippine',
             'nas-cent': 'nascent',
             # 'mid-1991': 'mid1991',
             'indepen-dent': 'independent',
             # 'mid-1980s': 'mid1980s',
             'lec-ture': 'lecture',
             'sub-ordinates.For': 'subordinates. For',
             'Tajik-istan': 'Tajikistan',
             'bor-der': 'border', 'net-work': 'network', 'formu-lated': 'formulated', 'train-ers': 'trainers',
             'boast-ing': 'boasting', 'facil-ity': 'facility', 'perpetra-tors': 'perpetrators',
             'sub-sequently': 'subsequently', 'per-sonnel': 'personnel', 'opera-tion': 'operation',
             'inter-mediaries': 'intermediaries', 'Pop-ular': 'Popular', 'coop-erate': 'cooperate',
             'pri-marily': 'primarily', 'relation-ship': 'relationship',
             'opera-tions.As': 'operations. As',
             'gov-ernments': 'governments',
             'pres-sure.At': 'pressure. At',
             'Secu-rity': 'Security',
             'sanc-tioned': 'sanctioned', 'pres-sure': 'pressure', 'cur-rency': 'currency', 'out-lays': 'outlays',
             'orga-nizational': 'organizational', 'refuel-ing': 'refueling',
             # 'Saudi-funded': 'Saudifunded',
             'accommo-date': 'accommodate', 'Pak-istan': 'Pakistan', 'insur-gencies': 'insurgencies',
             'intelli-gence': 'intelligence', 'registra-tion': 'registration', 'govern-ment': 'government',
             'rela-tionships': 'relationships', 'war-lords': 'warlords', 'con-tenders': 'contenders',
             'circum-spect': 'circumspect', 'inter-view': 'interview', 'Hus-sein': 'Hussein', 'mid-1998': 'mid1998',
             'ear-lier': 'earlier', 'devel-oping': 'developing', 'restric-tions': 'restrictions',
             'move-ment': 'movement', 'pur-chase': 'purchase',
             # 'bene-66': 'bene66',
             'avail-able': 'available',
             'sup-ported': 'supported', 'Mid-dle': 'Middle', 'ter-rorists': 'terrorists', 'with-out': 'without',
             'differ-ent': 'different', 'super-vision': 'supervision', 'pro-vided': 'provided',
             'opera-tives': 'operatives', 'Ban-shiri': 'Banshiri', 'com-plete': 'complete', 'sev-eral': 'several',
             # 'Afgha-68': 'Afgha68',
             'bomb-mak-ing': 'bomb-making', 'mes-sage': 'message', 'video-taped': 'videotaped',
             'evi-dence': 'evidence', 'impos-sible': 'impossible', 'insti-gation': 'instigation',
             'ter-rorism': 'terrorism',
             # 'B-2': 'B2',
             'under-ground': 'underground', 'sto-ries': 'stories',
             'investigat-ing': 'investigating', 'Sep-tember': 'September', 'characteriz-ing': 'characterizing',
             'South-ern': 'Southern', 'princi-pal': 'principal', 'char-acter': 'character',
             'simultane-ously.Khalid': 'simultaneously. Khalid',
             'cap-ture': 'capture', 'per-sons': 'persons',
             'pres-ent': 'present', 'dan-ger': 'danger', 'mani-festations': 'manifestations', 'deal-ing': 'dealing',
             'perform-ance': 'performance', 'career-enhanc-ing': 'career-enhancing', 'dupli-cation': 'duplication',
             'signif-icant': 'significant',
             'Intel-ligence.The': 'Intelligence. The',
             # 'congres-74': 'congres74',
             'dissi-dents.The': 'dissidents. The',
             'indi-viduals': 'individuals', 'guide-lines': 'guidelines',
             'mak-ing': 'making', 'dis-tinctly': 'distinctly', 'perpe-trators': 'perpetrators',
             'com-plement': 'complement', 'coop-eration': 'cooperation', 'repro-grammed': 'reprogrammed',
             'eco-nomic': 'economic',
             # 'des-76': 'des76',
             'counter-terrorism': 'counterterrorism',
             # 'mid-1990s': 'mid1990s',
             'analy-sis': 'analysis', 'sup-posed': 'supposed', 'appre-ciation': 'appreciation',
             'tac-tical': 'tactical', 'com-pleted': 'completed', 'Col-lection': 'Collection',
             'inad-equately': 'inadequately',
             # '16-week': '16week',
             'validat-ing': 'validating', 'shar-ing': 'sharing',
             'Counterintelli-gence': 'Counterintelligence', 'Divi-sion': 'Division',
             'counterterror-ism': 'counterterrorism', 'capa-bility': 'capability', 'crim-inal': 'criminal',
             'intel-ligence': 'intelligence', 'reg-ulated': 'regulated', 'con-cerns': 'concerns',
             'pros-ecutors': 'prosecutors', 'act-ing': 'acting',
             # 'information-sharing': 'informationsharing',
             'Depart-ment': 'Department', 'crimi-nal': 'criminal', 'inde-pendently': 'independently',
             'prac-tices': 'practices', 'pre-sented': 'presented',
             # 'inter-COUNTERTERRORISM': 'interCOUNTERTERRORISM',
             'fugi-tives': 'fugitives', 'per-haps': 'perhaps', 'seri-ously': 'seriously',
             # 'resources.Bor-der': 'resources.Border',
             'hear-ings': 'hearings',
             # 'pro-80': 'pro80',
             'Inspec-tors': 'Inspectors', 'fed-eral': 'federal', 'offi-cers': 'officers',
             'investiga-tion.The': 'investigation.The',
             'priori-ties': 'priorities', 'pro-tect': 'protect',
             'inves-tigation': 'investigation', 'indict-ing': 'indicting', 'Trans-portation': 'Transportation',
             'man-date': 'mandate', 'vul-nerable': 'vulnerable', 'pos-sibility': 'possibility', 'air-ports': 'airports',
             'lay-ered': 'layered',
             # '40-person': '40person',
             'avia-tion': 'aviation', 'rou-tinely': 'routinely',
             'long-time': 'longtime',
             # 'ter-COUNTERTERRORISM': 'terCOUNTERTERRORISM',
             'detec-tors': 'detectors',
             'exacer-bating': 'exacerbating', 'con-centrate': 'concentrate', 'pris-oners': 'prisoners',
             'rein-forced': 'reinforced', 'lead-ership': 'leadership', 'cab-inet': 'cabinet',
             'dis-seminates': 'disseminates', 'con-duct': 'conduct', 'frac-tion': 'fraction',
             'con-federated': 'confederated', 'commu-nity': 'community', 'presi-dent': 'president',
             'com-munications': 'communications', 'leverag-ing': 'leveraging', 'con-clusive': 'conclusive',
             'environ-ment': 'environment', 'telecommu-nications': 'telecommunications', 'col-lection': 'collection',
             'war-rants': 'warrants', 'vio-lating': 'violating', 'tech-nology': 'technology', 'dili-gent': 'diligent',
             'com-munication': 'communication', 'secu-rity': 'security', 'Dono-van': 'Donovan',
             'devel-oped': 'developed', 'Intelli-gence': 'Intelligence', 'Cen-tral': 'Central', 'sta-tions': 'stations',
             'cul-ture': 'culture',
             # 'promi-COUNTERTERRORISM': 'promiCOUNTERTERRORISM',
             'pub-lished': 'published',
             'Controver-sies': 'Controversies',
             'Service.Dur-ing': 'Service. During',
             'unde-niably': 'undeniably',
             'divi-dend': 'dividend', 'administra-tion': 'administration', 'guid-ance': 'guidance',
             'reallo-cated': 'reallocated', 'Angle-ton': 'Angleton', 'pene-tration': 'penetration',
             'Infor-mation': 'Information',
             # 'infor-COUNTERTERRORISM': 'inforCOUNTERTERRORISM',
             'quali-fied': 'qualified', 'budg-ets': 'budgets', 'relation-ships': 'relationships',
             'Countert-errorist': 'Counterterrorist', 'for-mal': 'formal', 'Direc-tor': 'Director',
             'sup-port': 'support', 'tal-ent': 'talent',
             # 'ultra-high-and': 'ultra-highand', # probably ultra-high-end
             'gen-eration': 'generation',
             'accus-tomed': 'accustomed',
             # 'Con-COUNTERTERRORISM': 'ConCOUNTERTERRORISM',
             'where-withal': 'wherewithal',
             'Bud-get': 'Budget', 'pol-icy': 'policy', 'pre-sumed': 'presumed', 'sec-retary': 'secretary',
             'inte-grate': 'integrate',
             # 'head-94': 'head94',
             'appoint-ing': 'appointing', 'Secre-tary': 'Secretary',
             'counterter-rorism': 'counterterrorism', 'for-gotten': 'forgotten', 'Con-gress': 'Congress',
             'sys-tem': 'system',
             # 'J-2': 'J2', 'J-3': 'J3',
             'dimin-ished': 'diminished', 'Ger-man': 'German',
             'Pen-tagon': 'Pentagon', 'dur-ing': 'during', 'ren-dezvous': 'rendezvous', 'fail-ure': 'failure',
             'Rea-gan': 'Reagan', 'pro-duced': 'produced', 'cau-tion': 'caution', 'max-imum': 'maximum',
             'coordina-tor': 'coordinator', 'offi-cial': 'official',
             'ter-rorism.However': 'terrorism. However',
             'hon-ored': 'honored',
             'casualties.Twenty-three': 'casualties. Twenty-three',
             'neces-sary.When': 'necessary. When',
             'hav-ing': 'having', 'reprogram-ming': 'reprogramming',
             'char-acterized': 'characterized', 'Con-tra': 'Contra', 'pro-ceeds': 'proceeds', 'coun-sel': 'counsel',
             'oth-ers': 'others',
             # 'oth-COUNTERTERRORISM': 'othCOUNTERTERRORISM',
             'nar-cotics': 'narcotics',
             'vet-eran': 'veteran', 'Coun-terterrorism': 'Counterterrorism', 'Revolu-tion': 'Revolution',
             'sover-eignty': 'sovereignty', 'civ-ilized': 'civilized', 'prom-ised': 'promised', 'Nei-ther': 'Neither',
             'bomb-ing': 'bombing', 'requir-ing': 'requiring', 'Presi-dential': 'Presidential', 'pre-cise': 'precise',
             'princi-pals': 'principals', 'commence-ment': 'commencement', 'con-trol': 'control',
             'terri-ble': 'terrible', 'Con-vention': 'Convention', 'power-ful': 'powerful', 'impor-tant': 'important',
             'con-sequence': 'consequence', 'with-hold': 'withhold', 'restric-tion': 'restriction',
             'effec-tive': 'effective', 'Intel-ligence': 'Intelligence',
             'govern-ment.While': 'government. While',
             'exam-ined': 'examined', 'implement-ing': 'implementing',
             'prior-ities.Presidents': 'priorities. Presidents',
             'glob-alization.Terrorism': 'globalization. Terrorism',
             'con-text': 'context', 'pro-grams': 'programs', 'Orga-nization': 'Organization',
             'Representa-tives': 'Representatives', 'juris-diction': 'jurisdiction', 'inte-grated': 'integrated',
             'investiga-tions': 'investigations',
             'concerns.Mem-bers': 'concerns. Members',
             'mat-ters': 'matters',
             'lead-ing': 'leading', 'pres-idents': 'presidents', 'commit-tees': 'committees', 'lit-tle': 'little',
             'splin-tered': 'splintered', 'sys-tematically': 'systematically', 'appar-ent': 'apparent',
             'Septem-ber': 'September',
             # 'ond-or': 'ondor',
             'crim-inals': 'criminals', 'individ-ual': 'individual',
             'commit-ted': 'committed', 'extrem-ist': 'extremist', 'sup-plied': 'supplied', 'gath-ered': 'gathered',
             'opera-tions': 'operations',
             # 'gov-RESPONSES': 'govRESPONSES',
             'Car-ney': 'Carney', 'cred-ible': 'credible',
             'out-standing': 'outstanding', 'reestab-lished': 'reestablished', 'gun-man': 'gunman',
             'activ-ities': 'activities', 'con-tacts': 'contacts', 'pub-licly': 'publicly', 'con-tinued': 'continued',
             'Tal-iban': 'Taliban', 'despi-cable': 'despicable', 'del-egation': 'delegation', 'pur-sued': 'pursued',
             'Jus-tice': 'Justice', 'trib-als': 'tribals',
             # '10-foot': '10foot',
             'out-skirts': 'outskirts',
             'land-ing': 'landing', 'acknowl-edged': 'acknowledged', 'sup-porters': 'supporters', 'wor-ried': 'worried',
             'Notifica-tion': 'Notification', 'pres-idential': 'presidential', 'Opera-tions': 'Operations',
             'con-gressional': 'congressional', 'per-cent': 'percent',
             'U.S.Attor-ney': 'U.S. Attorney',
             'oper-ation.Clarke': 'operation. Clarke', 'opera-tion.He': 'operation. He',
             'rec-ollection': 'recollection',
             'pub-licity.When': 'publicity. When',
             'open-ing': 'opening', 'representa-tive': 'representative',
             'discus-sion': 'discussion', 'pur-sue': 'pursue', 'bomb-ings': 'bombings', 'Sus-picion': 'Suspicion',
             'terror-ism': 'terrorism', 'think-ing': 'thinking', 'out-side': 'outside',
             'pharma-ceutical': 'pharmaceutical', 'biolog-ical': 'biological', 'respon-sible': 'responsible',
             'mis-siles.Though': 'missiles. Though',
             # '48-hour': '48hour',
             'coun-terparts': 'counterparts',
             'Vine-yard': 'Vineyard', 'Min-ister': 'Minister', 'sam-ple': 'sample', 'shap-ing': 'shaping',
             'over-all': 'overall', 'simul-taneous': 'simultaneous', 'empha-size': 'emphasize',
             'policy-makers': 'policymakers', 'pos-ing': 'posing', 'hun-dreds': 'hundreds',
             'sig-nificant': 'significant', 'threat-ening': 'threatening', 'Attor-ney': 'Attorney',
             'Commit-tee': 'Committee', 'con-nected': 'connected', 'Kho-bar': 'Khobar', 'Amer-icans': 'Americans',
             'ele-ment': 'element',
             'ripe.Acknowl-edging': 'ripe. Acknowledging',
             # 'one-off': 'oneoff',
             'train-ing': 'training', 'Econ-omist': 'Economist', 'world-wide': 'worldwide',
             # 'avail-120': 'avail120',
             'particu-lar': 'particular', 'insti-tutional': 'institutional', 'coun-terterrorism': 'counterterrorism',
             'dele-gates': 'delegates', 'Mul-lah': 'Mullah', 'rela-tions': 'relations',
             'cus-tody.The': 'custody. The',
             'depart-ment': 'department', 'des-ignate': 'designate', 'pre-vented': 'prevented',
             'sanc-tions': 'sanctions', 'Pak-istani': 'Pakistani', 'concen-trated': 'concentrated',
             'North-ern': 'Northern', 'ulti-mately': 'ultimately', 'frac-tious': 'fractious',
             'attrac-tive': 'attractive', 'spon-sor': 'sponsor', 'champi-oned': 'championed', 'dis-cussed': 'discussed',
             'vir-tually': 'virtually',
             'non-Muslims.The': 'nonMuslims. The',
             'Rus-sia': 'Russia',
             'com-plained': 'complained', 'Per-vez': 'Pervez', 'cre-ate': 'create', 'spec-ulated': 'speculated',
             'asso-ciated': 'associated', 'fre-quently': 'frequently', 'conver-sations': 'conversations',
             'mid-November': 'midNovember', 'pre-dict': 'predict', 'translat-ing': 'translating',
             'indict-ment': 'indictment', 'instal-lations.The': 'installations. The', 'specif-ically': 'specifically',
             'Khar-toum': 'Khartoum', 'Novem-ber': 'November', 'Presiden-tial': 'Presidential', 'al-Rahman': 'alRahman',
             'oper-ational': 'operational',
             'aircraft.Accord-ing': 'aircraft. According',
             # 'SA-7': 'SA7', 'SA-7s': 'SA7s',
             'asso-ciate': 'associate', 'com-merce': 'commerce', 'hijack-ing': 'hijacking', 'maxi-mum': 'maximum',
             'dis-cuss': 'discuss', 'Mauri-tanian': 'Mauritanian', 'Tom-ahawk': 'Tomahawk',
             'Kanda-har.The': 'Kandahar. The',
             'inno-cent': 'innocent', 'dam-age': 'damage', 'Jan-uary': 'January',
             'con-cern': 'concern', 'sight-ing': 'sighting', 'direc-tor': 'director', 'strengthen-ing': 'strengthening',
             'cap-tured': 'captured', 'fea-sible': 'feasible', 'tar-geting': 'targeting', 'Commis-sion': 'Commission',
             'Com-mission': 'Commission', 'col-laborators': 'collaborators', 'all-out': 'allout',
             # 'U-2': 'U2',
             'cover-age.Clarke': 'coverage. Clarke', 'car-ried': 'carried', 'reper-cussions': 'repercussions',
             'govern-ments': 'governments', 'fac-tor': 'factor',
             # 'AC-130': 'AC130',
             'electron-ics': 'electronics',
             'projec-tiles': 'projectiles',
             # 'AC-130s': 'AC130s',
             'unre-fueled': 'unrefueled', 'defer-ring': 'deferring',
             'for-ward': 'forward', 'how-ever': 'however',
             'unappealing.Pro-Taliban': 'unappealing. Pro-Taliban',
             'oper-ations.With': 'operations. With',
             'Oper-ations': 'Operations', 'per-spective': 'perspective',
             'expe-rienced': 'experienced', 'Spe-cial': 'Special', 'feasi-bility': 'feasibility',
             'invad-ing': 'invading', 'provoca-tion': 'provocation', 'hunt-ing': 'hunting', 'mis-siles': 'missiles',
             'report-ing': 'reporting', 'possi-ble': 'possible',
             # 'diplo-138': 'diplo138',
             'rad-icals': 'radicals',
             'rely-ing': 'relying', 'Mas-soud': 'Massoud', 'Never-theless': 'Nevertheless', 'Kan-dahar': 'Kandahar',
             'imag-ine': 'imagine', 'say-ing': 'saying', 'wari-ness': 'wariness', 'omi-nous': 'ominous',
             'mate-rial': 'material', 'pres-ence': 'presence', 'sum-mer': 'summer', 'mid-1999': 'mid1999',
             'rendi-tion': 'rendition', 'bet-ter': 'better', 'Counterter-rorist': 'Counterterrorist',
             'haz-ardous': 'hazardous', 'reluc-tance': 'reluctance', 'prob-ably': 'probably',
             'neigh-boring': 'neighboring', 'strong-willed': 'strongwilled', 'terror-ist': 'terrorist',
             'Hizbul-Ittihad': 'HizbulIttihad', 'knowl-edge': 'knowledge', 'ambigui-ties': 'ambiguities',
             'evalu-ated': 'evaluated', 'sug-gestion': 'suggestion', 'vio-lent': 'violent', '.-bound': '.bound',
             'authori-ties': 'authorities',
             # 'mid-1996': 'mid1996',
             'moun-tainous': 'mountainous',
             'activi-ties': 'activities',
             'Hambali.Ham-bali': 'Hambali. Hambali',
             'col-leagues.Though': 'colleagues. Though',
             'com-mitted': 'committed', 'out-dated': 'outdated',
             'recruit-ing': 'recruiting', 'emphasiz-ing': 'emphasizing', 'him-self': 'himself', 'Ham-bali': 'Hambali',
             'under-going': 'undergoing', 'organiza-tion': 'organization', 'nec-essary': 'necessary',
             # '.-educated': '.educated',
             'concen-trate': 'concentrate',
             '2000.Ham-bali': '2000. Hambali',
             'noti-fying': 'notifying', 'doc-umentaries': 'documentaries', 'rel-atives': 'relatives',
             'pro-posed': 'proposed', 'accord-ing': 'according', 'diffi-culty': 'difficulty', 'grad-uate': 'graduate',
             'con-sider': 'consider', 'build-ings': 'buildings', 'excep-tional': 'exceptional', 'pro-posal': 'proposal',
             'preoccupa-tion': 'preoccupation', 'unquestion-ably': 'unquestionably', 'Kanda-har.KSM': 'Kandahar. KSM',
             'bat-tle': 'battle', 'Khal-lad': 'Khallad', 'partici-pate': 'participate', '.-flagged': '.flagged',
             'fly-ing': 'flying', 'oper-ation': 'operation', 'cop-per': 'copper', 'com-bat': 'combat',
             'tele-phone': 'telephone', 'Cal-ifornia': 'California', 'soft-ware': 'software', 'Inter-net': 'Internet',
             # 'com-AL': 'comAL',
             'sched-ules': 'schedules', 'agen-cies': 'agencies', 'volun-teered': 'volunteered',
             'dif-ferent': 'different', 'prosthe-sis': 'prosthesis', 'toi-letries': 'toiletries',
             'trav-eled': 'traveled', 'Mihd-har': 'Mihdhar', 'Kanda-har.Though': 'Kandahar. Though',
             'stu-dents': 'students', 'aspir-ing': 'aspiring', 'flu-ency': 'fluency', 'per-suasive': 'persuasive',
             'sup-posedly': 'supposedly', 'fun-damentalism': 'fundamentalism', 'reli-gious': 'religious',
             'seek-ing': 'seeking', 'cut-ting': 'cutting', 'com-munity': 'community', 'sec-tion': 'section',
             'Emi-rates': 'Emirates', 'Emi-rati': 'Emirati', 'admis-sion': 'admission', 'mov-ing': 'moving',
             'coun-try.Although': 'country. Although', 'conse-quently': 'consequently', 'restau-rants': 'restaurants',
             'permis-sion': 'permission', 'comfort-ably': 'comfortably', 'afflu-ent': 'affluent',
             'Ger-many.There': 'Germany. There', 'daugh-ter': 'daughter',
             'apart-ment.Witnesses': 'apartment. Witnesses',
             'fre-quent': 'frequent', 'dress-ing': 'dressing', 'rel-ished': 'relished', 'evo-lution': 'evolution',
             'cit-izen': 'citizen', 'Binal-shibh': 'Binalshibh', 'com-puter': 'computer', 'Febru-ary': 'February',
             'acquain-tance': 'acquaintance', 'Motas-sadeq': 'Motassadeq', 'obtain-ing': 'obtaining',
             'mission.Binal-shibh': 'mission. Binalshibh', 'invi-tation': 'invitation',
             'oper-ation.That': 'operation. That', 'com-bination': 'combination', 'asso-ciates': 'associates',
             'Kanda-har': 'Kandahar', 'She-hhi': 'Shehhi', 'appear-ing': 'appearing', 'conspic-uous': 'conspicuous',
             'con-ceal': 'conceal', 'tak-ing': 'taking', 'avi-ation': 'aviation', 'Pre-sumably': 'Presumably',
             'appli-cations': 'applications', 'under-taken': 'undertaken', 'pass-port': 'passport',
             'flow-ing.To': 'flowing. To', 'cir-culated': 'circulated', 'dona-tions.Al': 'donations. Al',
             'char-itable': 'charitable', 'inter-nal': 'internal', 'wit-tingly': 'wittingly', 'con-tained': 'contained',
             'fund-raising': 'fundraising', 'organ-ization': 'organization', 'start-up': 'startup',
             'par-ticularly': 'particularly', 'dia-monds': 'diamonds', 'prac-tical': 'practical', 'fund-ing': 'funding',
             'for-eign': 'foreign', 'sub-stantial': 'substantial', 'facili-tator': 'facilitator', 'giv-ing': 'giving',
             'Ger-many': 'Germany', 'Finan-cial': 'Financial', 'direc-tion': 'direction',
             'indoctri-nate': 'indoctrinate', 'assess-ments': 'assessments', 'cap-turing': 'capturing',
             'delib-erate': 'deliberate', 'unnec-essary': 'unnecessary', 'Ameri-can': 'American',
             'Jor-danian': 'Jordanian', 'bod-ies': 'bodies', 'Decem-ber': 'December', 'communi-cated': 'communicated',
             'empty-handed': 'emptyhanded', 'Memoran-dum': 'Memorandum', 'over-seas': 'overseas',
             'fal-sified': 'falsified', 'Khal-dan': 'Khaldan', 'temper-atures': 'temperatures', 'admit-ted': 'admitted',
             'asy-lum': 'asylum', 'Vic-toria': 'Victoria', 'Cana-dian': 'Canadian', 'associ-ates': 'associates',
             'liq-uid': 'liquid', 'cooper-ating': 'cooperating', 'Clin-ton': 'Clinton', 'Mon-treal': 'Montreal',
             'domes-tic': 'domestic', 'inspec-tion': 'inspection', 'regu-lar': 'regular',
             # 'then-prevailing': 'thenprevailing',
             'vari-ety': 'variety', 'pre-pared': 'prepared',
             'develop-ing': 'developing', 'Mihd-har.Two': 'Mihdhar. Two', 'iden-tifier': 'identifier',
             'after-action': 'afteraction', 'nib-bling': 'nibbling', 'Com-mittee': 'Committee',
             # '.-Canada': '.Canada',
             'Mushar-raf': 'Musharraf', 'expul-sion': 'expulsion', 'offen-sive': 'offensive',
             'desper-ately': 'desperately', 'after-math': 'aftermath', 'suffi-cient': 'sufficient',
             'des-ignated': 'designated', 'Octo-ber': 'October', 'transac-tions': 'transactions', 'sys-tems': 'systems',
             'find-ing': 'finding', 'experi-ence': 'experience', 'intel-ligence.This': 'intelligence. This',
             'finan-cial': 'financial', 'else-where': 'elsewhere', 'Trea-sury': 'Treasury', 'launder-ers': 'launderers',
             'strat-egy': 'strategy', 'immi-gration': 'immigration', 'await-ing': 'awaiting', 'Ter-rorism': 'Terrorism',
             'estab-lish': 'establish', 'pow-erful': 'powerful', 'well-organ-ized': 'well-organized',
             'com-plex.Officers': 'complex. Officers', 'fight-ing': 'fighting', 'men-tioned': 'mentioned',
             'endors-ing': 'endorsing', 'south-ern': 'southern', 'chil-dren': 'children', 'frustra-tion': 'frustration',
             'heli-copters': 'helicopters', 'chap-ter': 'chapter', 'Admi-ral': 'Admiral', 'chair-man': 'chairman',
             # '60-day': '60day',
             'con-sidering': 'considering', 'bio-logical': 'biological', 'com-pound': 'compound',
             'dis-ruptions': 'disruptions', 'compla-cency': 'complacency', 'prepar-ing': 'preparing',
             'eventu-ally': 'eventually', 'Fol-lowing': 'Following', 'Kash-mir': 'Kashmir', 'Bar-bara': 'Barbara',
             'interroga-tions': 'interrogations', 'inter-vened': 'intervened', 'Pak-istan.The': 'Pakistan. The',
             'inter-mediary': 'intermediary',
             # 'Yeme-192': 'Yeme192',
             'Sim-ilarly': 'Similarly', 'writ-ten': 'written',
             'equiv-ocating': 'equivocating', 'prin-cipals': 'principals', 'increas-ingly': 'increasingly',
             'com-mander': 'commander', 'contin-gency': 'contingency', 'conclu-sion': 'conclusion',
             'person-ally': 'personally',
             # 'ter-194': 'ter194',
             'circumstan-tial': 'circumstantial',
             'cru-cial': 'crucial', 'threaten-ing': 'threatening', 'pre-liminary': 'preliminary',
             'reser-vations': 'reservations', 'last-minute': 'lastminute', 'lock-ing': 'locking',
             'enforce-ment': 'enforcement', 'rudimen-tary': 'rudimentary', 'infor-196': 'infor196',
             'encour-aged': 'encouraged', 'elimi-nate': 'eliminate',
             # 'command-and-control': 'command-andcontrol',
             'cam-paign': 'campaign',
             # '36-day': '36day',
             'adminis-tration': 'administration',
             # 'Israeli-Palestinian': 'IsraeliPalestinian',
             'presen-tations': 'presentations', 'brief-ing': 'briefing',
             'admin-istration': 'administration', 'par-ticular': 'particular', 'col-lapse': 'collapse',
             # 'Deci-FROM': 'DeciFROM',
             'coordi-nate': 'coordinate', 'Prin-cipals': 'Principals',
             'decisionmak-ing': 'decisionmaking', 'signifi-cant': 'significant',
             'remained.Working-level': 'remained. Workinglevel',
             'cabi-net': 'cabinet', 'sub-cabinet': 'subcabinet',
             'DCI.Pres-ident': 'DCI. President', 'pri-ority': 'priority', 'iden-tify': 'identify',
             'memo-randum': 'memorandum', 'inaugu-ration': 'inauguration', 'fig-ure': 'figure',
             'conse-quence': 'consequence', 'ineffec-tual': 'ineffectual', 'retali-ate': 'retaliate',
             'counterproduc-tive': 'counterproductive', 'increas-ing': 'increasing', 'propos-als': 'proposals',
             'presi-dential': 'presidential', 'Regard-ing': 'Regarding',
             # 'anti-Taliban': 'antiTaliban',
             'compre-hensive': 'comprehensive', 'pre-paredness.The': 'preparedness. The', 'pro-gram': 'program',
             'presiden-tial': 'presidential', 'multi-year': 'multiyear', 'sanctu-aries': 'sanctuaries',
             'cybersecu-rity': 'cybersecurity', 'pro-gram.As': 'program. As', 'for-mally': 'formally',
             'over-throwing': 'overthrowing',
             # 'accom-206': 'accom206',
             'neg-ative': 'negative',
             '.-Pakistani': '.Pakistani', 'vig-orously': 'vigorously', 'diplo-matic': 'diplomatic',
             'ini-tiatives': 'initiatives',
             # '.-Saudi': '.Saudi',
             # 'Secre-FROM': 'SecreFROM',
             'quad-rennial': 'quadrennial', 'Preda-tor': 'Predator', 'direc-tive': 'directive',
             'investiga-tion': 'investigation', 'testi-fied': 'testified',
             # 'act-FROM': 'actFROM',
             'main-tained': 'maintained', 'pend-ing': 'pending', 'proce-dures': 'procedures', 'hop-ing': 'hoping',
             'out-weighs': 'outweighs', 'mini-mize': 'minimize', 'execu-tive': 'executive',
             # 'mid-2001': 'mid2001',
             'mis-sile': 'missile', 'McLaugh-lin': 'McLaughlin', 'hit-ting': 'hitting', 'con-tinue': 'continue',
             'mas-terful': 'masterful', 'Invok-ing': 'Invoking', 'author-ities': 'authorities',
             'sug-gested.Treasury': 'suggested. Treasury', 'impli-cations': 'implications', 'Wol-fowitz': 'Wolfowitz',
             'simi-lar': 'similar', 'infrastruc-ture': 'infrastructure', 'circu-lated': 'circulated',
             'bun-galow': 'bungalow', 'camera-man': 'cameraman', 'three-phase': 'threephase', 'ele-ments': 'elements',
             'excep-tion': 'exception', 'break-ing': 'breaking', 'inabil-ity': 'inability', 'assis-tance': 'assistance',
             'Khal-lam': 'Khallam', 'specula-tion': 'speculation', 'Ange-les': 'Angeles',
             'fundamental-ist': 'fundamentalist', 'support-ive': 'supportive',
             # 'associ-216': 'associ216',
             'worship-pers': 'worshippers', 'Bay-oumi': 'Bayoumi', 'Abdul-lah': 'Abdullah',
             'encoun-tered': 'encountered', 'col-lect': 'collect', 'Mih-dhar': 'Mihdhar', 'Feb-ruary': 'February',
             'ver-sion': 'version', 'dis-sembled': 'dissembled', 'involve-ment': 'involvement',
             # 'arriv-218': 'arriv218',
             'dove-tail': 'dovetail', 'help.Bay-oumi': 'help.Bayoumi', 'posses-sions': 'possessions',
             'expen-sive': 'expensive',
             # '30-day': '30day',
             'indi-vidual': 'individual',
             'administra-tor': 'administrator', 'lan-guage': 'language', 'pho-tos': 'photos',
             'Bakar-bashat': 'Bakarbashat', 'rela-tionship': 'relationship',
             # 'mid-2000': 'mid2000',
             'Vir-ginia.As': 'Virginia. As', 'land-ings': 'landings', 'evi-denced': 'evidenced',
             'regis-tration': 'registration', 'meth-ods.When': 'methods.When',
             'trans-action.After': 'transaction. After', 'Fran-cisco': 'Francisco', 'far-ing': 'faring',
             'interna-tional': 'international', 'Nor-man': 'Norman', 'Pro-gram': 'Program', 'trans-fers': 'transfers',
             'sta-tus': 'status', 'instruc-tor': 'instructor', 'Sheh-hi': 'Shehhi', '16-room': '16room',
             'dor-mitory': 'dormitory', 'back-ground': 'background', 'Califor-nia': 'California', 'Ari-zona': 'Arizona',
             'dis-continue': 'discontinue',
             # 'per-226': 'per226',
             'accom-panying': 'accompanying',
             'return-ing': 'returning', 'occa-sion': 'occasion', 'assess-ment': 'assessment', 'Repub-lic': 'Republic',
             'stay-ing': 'staying', 'mail-box': 'mailbox', 'some-time': 'sometime', 'nor-mally': 'normally',
             'set-tle.They': 'settle. They', 'room-mates': 'roommates', 'Jer-sey.As': 'Jersey. As',
             'con-tact': 'contact',
             'rec-ommended': 'recommended', 'partic-ipate': 'participate', 'rea-sons': 'reasons', 'eas-ier': 'easier',
             'inexperi-ence': 'inexperience', 'Chech-nya': 'Chechnya', 'bor-der.Upon': 'border. Upon',
             # 'help-THE': 'helpTHE',
             'deter-mining': 'determining', 'fit-ness': 'fitness', 'sui-cide': 'suicide',
             'report-edly': 'reportedly', 'Eng-lish': 'English', 'logis-tical': 'logistical',
             'safe-house': 'safehouse',  # ?
             'numer-ous': 'numerous', 'deci-sion': 'decision', 'Baniham-mad': 'Banihammad',
             'Arabia.Khal-lad': 'Arabia. Khallad', 'Hezbol-lah': 'Hezbollah', 'focus-ing': 'focusing',
             'coordi-nating': 'coordinating', 'mail-boxes': 'mailboxes',
             # 'mid-June': 'midJune',
             'cross-country': 'crosscountry', 'Hort-man': 'Hortman', 'receiv-ing': 'receiving',
             'sim-ulator': 'simulator', 'mus-cle': 'muscle', 'paral-lel': 'parallel', 'ini-tial': 'initial',
             'per-sonally': 'personally', 'sub-ject': 'subject', 'more-over': 'moreover', 'sub-sequent': 'subsequent',
             'disagree-ment': 'disagreement', 'differ-ences.Binalshibh': 'differences. Binalshibh',
             # 'mid-July': 'midJuly',
             'Not-ing': 'Noting', 'Mous-saoui': 'Moussaoui',
             'attacks.More-over': 'attacks. Moreover',
             # 'Atta-Binalshibh': 'AttaBinalshibh',
             'assign-ment': 'assignment',
             'revis-ited': 'revisited', 'Kah-tani.Upon': 'Kahtani. Upon', 'Kah-tani': 'Kahtani',
             'coor-dinate': 'coordinate', 'credi-ble': 'credible', 'aero-nautical': 'aeronautical',
             'station.Accord-ing': 'station. According', 'stress-ing': 'stressing',
             # 'near-term': 'nearterm',
             'empha-sis': 'emphasis', 'fig-ures': 'figures', 'ideo-logical': 'ideological', 'pre-ferred': 'preferred',
             'Tali-ban': 'Taliban', 'assas-sination': 'assassination', 'remem-bers': 'remembers',
             'trans-fer': 'transfer', 'Mary-land': 'Maryland', 'Mass-achusetts': 'Massachusetts',
             'fragmen-tary': 'fragmentary', 'coor-dinator': 'coordinator', 'nondis-seminated': 'nondisseminated',
             'res-idence': 'residence', 'ana-lysts': 'analysts', 'gener-ally': 'generally', 'Avia-tion': 'Aviation',
             'possi-bly': 'possibly', 'com-pared': 'compared',
             # 'G-8': 'G8',
             'proba-bility': 'probability',
             'casu-alties': 'casualties', 'tel-evision': 'television', 'nec-essarily': 'necessarily',
             'indi-cating': 'indicating', 'Plan-ning': 'Planning',
             # 'pro-“': 'pro“',
             'antiair-craft': 'antiaircraft',
             'distribu-tion': 'distribution',
             # 'com-258': 'com258',
             'meas-ures.This': 'measures. This',
             'con-ference': 'conference', 'dis-rupt': 'disrupt', 'men-tion': 'mention', 'Ara-bian': 'Arabian',
             'hijack-ings': 'hijackings', 'lug-gage': 'luggage', 'vol-ume': 'volume', 'indefi-nitely': 'indefinitely',
             'occa-sions': 'occasions', 'sum-marizing': 'summarizing', 'oper-ative': 'operative',
             'desper-ate': 'desperate', 'unspeci-fied': 'unspecified', 'dra-matic': 'dramatic',
             'reg-ularly': 'regularly', 'con-trast': 'contrast', 'representa-tives': 'representatives',
             'per-ceive': 'perceive', 'indi-cation': 'indication', 'con-ducted': 'conducted',
             'pre-viously': 'previously',
             'tar-gets.Ashcroft': 'targets. Ashcroft',
             'sur-veillance': 'surveillance',
             'opportu-nity': 'opportunity', 'mis-takes': 'mistakes', 'Janu-ary': 'January',
             'oppor-tunities': 'opportunities', 'han-dling': 'handling',
             'ear-lier.The': 'earlier. The',
             'identifi-cation.DCI': 'identification. DCI',
             'evi-dent': 'evident', 'individ-uals': 'individuals',
             # 'Cole-related': 'Colerelated',
             'photo-graphs': 'photographs', 'photo-graphs.When': 'photographs. When',
             'pho-tographs': 'photographs', 'ques-tions': 'questions',
             # 'heads-up': 'headsup',
             'govern-ing': 'governing',
             'exist-ing': 'existing', 'investiga-tive': 'investigative', 'par-ticipants': 'participants',
             'inter-est': 'interest', 'the-ories': 'theories', 'recommen-dations': 'recommendations',
             'Man-agers': 'Managers', 'ana-lyzed': 'analyzed', 'repre-sentative': 'representative',
             'viola-tion': 'violation', 'Min-neapolis': 'Minneapolis', 'Lon-don': 'London', 'per-sonal': 'personal',
             'some-one': 'someone', 'Dis-covering': 'Discovering', 'undiscov-ered': 'undiscovered',
             'analyti-cal': 'analytical',
             # 'Al-Ballushi': 'AlBallushi',
             'Recogniz-ing': 'Recognizing',
             'col-leagues': 'colleagues', 'com-municated': 'communicated', 'pos-sibly': 'possibly', 'jut-ted': 'jutted',
             'bound-aries': 'boundaries', 'hel-icopter': 'helicopter',
             'a1,500-pound': 'a 1,500-pound',
             'deto-nated': 'detonated', 'Fluores-cent': 'Fluorescent', 'com-mand': 'command',
             'emer-gencies': 'emergencies', 'war-dens': 'wardens', 'trans-ferred': 'transferred',
             'morn-ing.Although': 'morning. Although', 'sepa-rate': 'separate', 'pro-cedures': 'procedures',
             'The40,000-officer': 'The 40,000-officer',
             'emer-gency': 'emergency', 'cen-tral': 'central',
             'chan-nels': 'channels', 'The11,000-member': 'The 1,000-member', 'divi-sion': 'division',
             'lad-der': 'ladder',
             'lieu-tenant': 'lieutenant', 'lim-ited': 'limited', 'compa-nies': 'companies', 'res-cue': 'rescue',
             'concern-ing': 'concerning', '1946.Fire-fighter': '1946. Firefighter', 'Man-agement': 'Management',
             'frequen-cies': 'frequencies', 'build-ing': 'building', 'elim-inate': 'eliminate',
             'accom-plish': 'accomplish', 'hap-pened': 'happened', 'por-tion': 'portion',
             # 'eyewit-HEROISM': 'eyewitHEROISM',
             'Author-ity': 'Authority', 'relat-ing': 'relating',
             'deter-mination': 'determination', 'dis-patchers': 'dispatchers',
             # 'civil-286': 'civil286',
             'imme-diately': 'immediately', 'evacua-tion': 'evacuation',
             # 'ground-floor': 'groundfloor',
             'com-panies': 'companies', 'con-sisted': 'consisted', 'fire-ball': 'fireball', 'speak-ing': 'speaking',
             'eleva-tors': 'elevators', 'firefight-ing': 'fire-fighting',
             # 'suppres-290': 'suppres290',
             'even-tually': 'eventually', 'para-medics': 'paramedics', 'immedi-ately': 'immediately',
             'hel-iport': 'heliport', 'res-cued': 'rescued',
             # 'offi-292': 'offi292', '17-minute': '17minute',
             'dou-bled': 'doubled',
             # '78th-floor': '78thfloor',
             'Dam-age': 'Damage', 'dem-olition': 'demolition',
             # '82nd-floor': '82ndfloor',
             'gen-erally': 'generally', 'sud-denly': 'suddenly', 'func-tion': 'function',
             'announce-ments': 'announcements', 'over-whelmed': 'overwhelmed', 'oper-ators': 'operators',
             'sug-gests': 'suggests', 'stair-wells': 'stairwells', 'evac-uate.The': 'evacuate. The',
             'previ-ously': 'previously',
             # 'stair-296': 'stair296',
             'over-weight': 'overweight',
             'stair-well': 'stairwell', 'pro-nounced': 'pronounced', 'communica-tions': 'communications',
             'activa-tion': 'activation', 'mas-ter': 'master', 'dif-ficult': 'difficult', 'vary-ing': 'varying',
             'tacti-cal': 'tactical', 'effective-ness': 'effectiveness', 'learn-ing': 'learning',
             'ele-vator': 'elevator', 'communi-cate': 'communicate', 'chan-nel': 'channel', 'Lib-erty': 'Liberty',
             'approxi-mately': 'approximately', 'addi-tional': 'additional', 'Brook-lyn': 'Brooklyn',
             'fatal-ities': 'fatalities', 'communicat-ing': 'communicating', 'con-versation': 'conversation',
             'respon-der': 'responder', 'check-ing': 'checking', 'imme-diately.While': 'immediately. While',
             'civil-ians': 'civilians', 'disori-ented': 'disoriented', 'evacu-ation': 'evacuation',
             # '90-something': '90something',
             'dis-patcher': 'dispatcher',
             # '44th-floor': '44thfloor', 'mid-20s': 'mid20s',
             'man-ning': 'manning', 'com-manders': 'commanders', 'neighbor-ing': 'neighboring',
             'prox-imity': 'proximity', 'win-dows': 'windows', 'suf-fered': 'suffered', 'dis-patch': 'dispatch',
             'evac-uation': 'evacuation', 'collapsed.How-ever': 'collapsed. However', 'fire-fighters': 'firefighters',
             'reas-cend': 'reascend', 'col-lapsed': 'collapsed', 'firefight-ers': 'firefighters',
             'actu-ally': 'actually', 'con-course': 'concourse', 'fire-fighter': 'firefighter', 'clos-est': 'closest',
             'unfath-omable': 'unfathomable', 'How-ever': 'However', 'evac-uate': 'evacuate',
             'Superin-tendent': 'Superintendent',
             # 'les-HEROISM': 'lesHEROISM',
             'Addi-tionally': 'Additionally',
             'sur-rounding': 'surrounding', 'Fair-fax': 'Fairfax', 'exer-cise': 'exercise', 'exac-erbate': 'exacerbate',
             'prob-lematic': 'problematic', 'occu-pants': 'occupants', 'prelim-inary': 'preliminary',
             'volun-teer': 'volunteer', 'individu-als': 'individuals', 'private-sector': 'privatesector',
             'impass-able': 'impassable', 'ini-tially': 'initially', 'con-fusion': 'confusion',
             'up-to-date': 'upto-date', 'prob-ability': 'probability', 'work-place': 'workplace',
             'Emergen-cies': 'Emergencies', 'exam-ple': 'example', 'uni-fied': 'unified', 'magni-tude': 'magnitude',
             '16-acre': '16acre', 'diffi-cult': 'difficult', 'Fur-thermore': 'Furthermore', 'mobi-lizing': 'mobilizing',
             'capa-bilities': 'capabilities', 'agencies.Cer-tainly': 'agencies. Certainly',
             'inte-grating': 'integrating', 'com-municate': 'communicate', 'coordi-nated': 'coordinated',
             'responders.Nev-ertheless': 'responders. Nevertheless', 'Amer-ica': 'America', 'objec-tive': 'objective',
             'appro-priate': 'appropriate', 'the-ater': 'theater', 'Con-dition': 'Condition', 'strand-ing': 'stranding',
             'imple-mented': 'implemented', 'Manage-ment': 'Management', 'flow-ing': 'flowing',
             'Manhat-tan': 'Manhattan', 'impro-vised': 'improvised', 'sys-tem.Vice': 'system. Vice',
             'mini-mization': 'minimization', 'con-nections': 'connections', 'reca-pitulated': 'recapitulated',
             'interven-tion': 'intervention', 'rep-resentative': 'representative', 'meet-ing': 'meeting',
             'per-petrators': 'perpetrators', 'support-ing': 'supporting', 'over-arching': 'overarching',
             'terror-ism.The': 'terrorism. The', 'stand-ing': 'standing',
             # 'Political-Military': 'PoliticalMilitary',
             'brief-ings': 'briefings', 'disap-pointing': 'disappointing', 'oper-ations.He': 'operations. He',
             'har-bor': 'harbor', 'Sad-dam': 'Saddam', 'unconven-tional': 'unconventional', 'inter-ested': 'interested',
             'inter-ests': 'interests',
             # 'pri-WARTIME': 'priWARTIME',
             'fol-lowing': 'following',
             'con-templated': 'contemplated', 'top-ple': 'topple', 'coali-tion': 'coalition', 'Pash-tun': 'Pashtun',
             'hun-dred': 'hundred', 'Comment-ing': 'Commenting', 'sig-nal': 'signal', 'soci-eties': 'societies',
             'mix-ture': 'mixture', 'pre-eminent': 'preeminent', 'uncom-promising': 'uncompromising',
             'Ser-bia': 'Serbia', 'cleans-ing': 'cleansing', 'con-gregate': 'congregate', 'target-ing': 'targeting',
             # 'sen-FORESIGHT': 'senFORESIGHT',
             'Evad-ing': 'Evading', 'out-put': 'output',
             # '30-to': '30to',
             'dis-counted': 'discounted', 'seri-ous': 'serious', 'unprece-dented': 'unprecedented',
             'gov-ernment.The': 'government. The',
             'con-troversial': 'controversial', 'Ameri-cans': 'Americans',
             'inter-cepts': 'intercepts', 'prison-ers': 'prisoners', 'per-manent': 'permanent',
             'intend-ing': 'intending', 'res-olution': 'resolution', 'dia-logue': 'dialogue', 'car-rying': 'carrying',
             'scenar-ios.The': 'scenarios. The',
             'sur-prise': 'surprise', 'indi-cators': 'indicators',
             'dan-gerous': 'dangerous', 'recom-mendations': 'recommendations', 'explosives-laden': 'explosivesladen',
             'collec-tion': 'collection',
             # 'terrorist-controlled': 'terroristcontrolled',
             'ana-lyze': 'analyze',
             'deter-rence': 'deterrence', 'cit-izens': 'citizens', 'sanc-tuary.The': 'sanctuary. The',
             'lieu-tenants': 'lieutenants', 'mid-1997': 'mid1997', 'indica-tion': 'indication', 'sta-tion': 'station',
             'Shel-ton': 'Shelton', 'con-sistently': 'consistently', 'cir-cle': 'circle', 'unhap-piness': 'unhappiness',
             'danger-ous': 'dangerous',
             # 'unde-FORESIGHT': 'undeFORESIGHT',
             'consider-able': 'considerable',
             'sce-nario': 'scenario', 'capabil-ities': 'capabilities', 'sepa-rating': 'separating',
             'spe-cialists': 'specialists', 'prescrib-ing': 'prescribing', 'govern-ment.This': 'government. This',
             'Salem.Working-level': 'Salem.Workinglevel', 'compan-ion': 'companion', 'identi-fied': 'identified',
             'sig-nificance': 'significance', 'sur-veilled': 'surveilled',
             # 'pre-9/11': 'pre9/11',
             'plan.Accomplish-ing': 'plan. Accomplishing', 'fol-lowed': 'followed', 'every-one': 'everyone',
             'signifi-cance': 'significance', 'con-nect': 'connect', 'ten-sion': 'tension', 'examin-ing': 'examining',
             'hand-ful': 'handful', 'combat-ing': 'combating', 'countert-errorism': 'counterterrorism',
             'infor-mation.That': 'information. That', 'depart-ments': 'departments', 'cus-tody': 'custody',
             'news-cast.The': 'newscast. The', 'terrorism.Front-page': 'terrorism. Front-page',
             'resolved.Back-page': 'resolved. Back-page', 'inter-national': 'international',
             'headquar-tered': 'headquartered', 'elec-tricity': 'electricity', 'reli-gion': 'religion',
             'economi-cally': 'economically',
             # 'intelli-WHAT': 'intelliWHAT',
             'ter-rorism.Terrorists': 'terrorism. Terrorists', 'Responsi-bilities': 'Responsibilities',
             'lim-itless.Goals': 'limitless. Goals', 'objec-tives': 'objectives', 'capa-ble': 'capable',
             'per-sonalities': 'personalities',
             # 'par-364': 'par364',
             'enti-tled': 'entitled', 'a9/11-scale': 'a 9/11-scale',
             'cata-strophic': 'catastrophic', 'trust-worthiness': 'trustworthiness',
             'oper-ations.The': 'operations. The', 'net-works': 'networks', 'gov-erned': 'governed',
             'gover-nance': 'governance', 'con-trols': 'controls', 'vio-lence': 'violence', 'demo-cratic': 'democratic',
             # 'north-south': 'northsouth',
             'our-selves': 'ourselves', 'dis-putes': 'disputes',
             'long-standing': 'longstanding', 'com-mitments': 'commitments', 'cur-rent': 'current',
             'Assis-tance': 'Assistance', 'dis-tant': 'distant', 'reveal-ing': 'revealing', 'allo-cating': 'allocating',
             'con-sideration': 'consideration', 'substan-tial': 'substantial', 'con-tinuing': 'continuing',
             'war-lord': 'warlord', 'abil-ity': 'ability', 'min-imum': 'minimum', 'woe-fully': 'woefully',
             'U.S.gov-ernment': 'U.S. government', 'Wah-habi': 'Wahhabi', 'cul-tural': 'cultural',
             'appreci-ated': 'appreciated', 'reli-giously': 'religiously', 'contend-ing': 'contending',
             'Develop-ment': 'Development', 'friend-ship': 'friendship', 'atten-tion': 'attention',
             'popu-lation': 'population', 'popu-lar': 'popular', 'fash-ionable': 'fashionable', 'mes-sages': 'messages',
             'popula-tion': 'population', 'neighbors.Amer-ica': 'neighbors. America', 'noth-ing': 'nothing',
             'moder-ate': 'moderate', 'participa-tion': 'participation', 'dom-inant': 'dominant',
             'won-dered': 'wondered', 'prom-ising': 'promising', 'Gover-nors': 'Governors',
             'oppor-tunity.The': 'opportunity. The', 'linked.Com-merce': 'linked. Commerce',
             'control-ling': 'controlling',
             # '.-Israeli': '.Israeli',
             'agree-ments': 'agreements',
             'dra-matically': 'dramatically', 'strate-gies': 'strategies', 'sum-mit': 'summit',
             'cooper-ation': 'cooperation', 'con-structive': 'constructive', 'bal-ance': 'balance',
             'con-flicts': 'conflicts', 'con-flict': 'conflict', 'con-sidered': 'considered',
             'obli-gation': 'obligation', 'com-mercially': 'commercially',
             # 'non-NATO': 'nonNATO',
             'Pre-venting': 'Preventing', 'chal-lenges': 'challenges', 'mech-anisms': 'mechanisms',
             'rela-tively': 'relatively', 'per-suading': 'persuading', 'char-ities': 'charities',
             'consid-erable': 'considerable', 'elab-orate': 'elaborate', 'con-taining': 'containing',
             'ille-gally': 'illegally', 'matter.Pub-lic': 'matter. Public', 'origi-nating': 'originating',
             'counter-feit': 'counterfeit', 'vulnera-ble': 'vulnerable', 'immigra-tion': 'immigration',
             'poten-tially': 'potentially', 'cur-rently': 'currently', 'detec-tion': 'detection',
             'serv-ices': 'services', 'architec-ture': 'architecture', 'effi-ciency': 'efficiency',
             'numer-ical': 'numerical', 'dig-itized': 'digitized', 'trav-elers': 'travelers', 'intu-itive': 'intuitive',
             'dis-cretion': 'discretion', 'trans-portation': 'transportation',
             'counterterrorism.Inte-grating': 'counterterrorism. Integrating', 'biomet-ric': 'biometric',
             'Immi-grant': 'Immigrant', 'travel-ers': 'travelers', 'watch-list.These': 'watchlist. These',
             'Mexicans.Cur-rently': 'Mexicans. Currently', 'identifi-cation.The': 'identification. The',
             'fre-quency': 'frequency', 'con-sular': 'consular', 'mod-ern': 'modern', 'Over-all': 'Overall',
             'deci-sionmaking': 'decision-making',
             'pri-vacy': 'privacy', 'finger-prints': 'fingerprints',
             'obli-gations': 'obligations', 'prob-lem': 'problem', 'oppor-tunity': 'opportunity',
             'con-vinced': 'convinced', 'prior-ities': 'priorities', 'pri-vate': 'private',
             'unattain-able': 'unattainable', 'achiev-ing': 'achieving', 'technolo-gies': 'technologies',
             'transporta-tion': 'transportation', 'mul-tiple': 'multiple', 'poten-tial': 'potential',
             'cer-tain': 'certain', 'suc-cessor': 'successor', 'per-formed': 'performed', 'spe-cial': 'special',
             'mit-igating': 'mitigating', 'deploy-ment': 'deployment', 'techno-logical': 'technological',
             'facil-itate': 'facilitate', 'gov-ernmental': 'governmental',
             # 'ade-394': 'ade394',
             'pro-tection': 'protection', 'ade-quate': 'adequate', 'suc-cess': 'success', 'defend-ing': 'defending',
             'pro-tecting': 'protecting', 'exec-utive': 'executive', 'deliv-ering': 'delivering',
             'concen-trates': 'concentrates', 'vulnerabil-ity': 'vulnerability', 'prepared-ness': 'preparedness',
             'dis-tribution': 'distribution', 'accor-dance': 'accordance', 'enough.Team-work': 'enough. Teamwork',
             'suc-cessful': 'successful', 'reg-ular': 'regular',  # 'multi-jurisdictional': 'multijurisdictional',
             'pro-mote': 'promote', 'required.Con-gress': 'required. Congress', 'sec-tor': 'sector',
             'Prepared-ness': 'Preparedness', 'pre-paredness': 'preparedness', 'assess-ing': 'assessing',
             'Private-sec-tor': 'Private-sector', 'visi-ble': 'visible', 'incremen-tal': 'incremental',
             'struc-tures.They': 'structures. They', 'con-necting': 'connecting', 'Respon-sibility': 'Responsibility',
             'quan-tity': 'quantity', 'multi-plied': 'multiplied', 'Ter-rorist': 'Terrorist',
             'vulnerabili-ties': 'vulnerabilities', 'hav-HOW': 'havHOW', 'con-structed': 'constructed',
             'Home-land': 'Homeland', 'sift-ing': 'sifting', 'occa-sionally': 'occasionally', 'caus-ing': 'causing',
             'meet-ings': 'meetings', 'imple-mentation': 'implementation',
             # 'J-5': 'J5',
             'transna-tional': 'transnational', 'Exec-utive': 'Executive', 'con-cur': 'concur',
             'represen-tatives': 'representatives', 'cen-tralization': 'centralization', 'pres-ident': 'president',
             'Rums-feld': 'Rumsfeld', 'construc-tion': 'construction', 'inte-gration': 'integration',
             'Inte-gration': 'Integration', 'prob-lems': 'problems', 'all-source': 'allsource',
             # 'Goldwater-Nichols': 'GoldwaterNichols',
             'Coun-terintelligence': 'Counterintelligence',
             'Investiga-tion': 'Investigation', 'Pro-tection': 'Protection', 'oper-ate': 'operate',
             'trans-formation': 'transformation', 'devel-opments': 'developments', 'tech-nical': 'technical',
             'Usu-ally': 'Usually', 'concur-rence': 'concurrence', 'ground.Thought-ful': 'ground.Thoughtful',
             'rank-ing': 'ranking', 'pro-posals': 'proposals', 'nom-inations': 'nominations', 'Analy-sis': 'Analysis',
             'secre-tary': 'secretary', 'is-ill': 'isill',
             'll-So': 'llSo',
             'responsi-bilities': 'responsibilities',
             'policymak-ing': 'policymaking', 'out-weighed': 'outweighed', 'coun-seled': 'counseled',
             'capabili-ties': 'capabilities', 'rebuild-ing': 'rebuilding', 'clan-destine': 'clandestine',
             'bil-lions': 'billions', 'appropria-tions': 'appropriations', 'intelli-gence.The': 'intelligence. The',
             'disclo-sure': 'disclosure', 'sys-temic': 'systemic',
             # 'immigra-416': 'immigra416',
             'frus-trations': 'frustrations', 'demon-strated': 'demonstrated', 'implic-itly': 'implicitly',
             'Counterin-telligence': 'Counterintelligence', 'compartmenta-tion': 'compartmentation',
             'over-classifying': 'overclassifying', 'pro-moting': 'promoting', 'mean-ingful': 'meaningful',
             'hub-and-spoke': 'hub-andspoke', 'data-base': 'database', 'net-work.An': 'network. An',
             'con-verted': 'converted', 'data-bases': 'databases', 'protect-ing': 'protecting', 'par-ties': 'parties',
             # 'policy-HOW': 'policyHOW',
             'pre-serve': 'preserve', 'authoriz-ing': 'authorizing', 'stud-ies': 'studies',
             'con-suming': 'consuming', 'commit-tee': 'committee', 'con-solidate': 'consolidate',
             'disrup-tion': 'disruption', 'main-taining': 'maintaining',
             # 'pos-422': 'pos422', 'MI-5': 'MI5',
             'dis-closed': 'disclosed', 'inves-tigations': 'investigations', 'pro-cessing': 'processing',
             'exacer-bate': 'exacerbate', 'coop-erating': 'cooperating', 'con-cerning': 'concerning',
             'inves-tigative': 'investigative', 'ded-icated': 'dedicated',
             # 'inves-424': 'inves424',
             'prerequi-site': 'prerequisite', 'mis-sion.This': 'mission.This', 'appro-priately': 'appropriately',
             'qualifi-cations': 'qualifications', 'assim-ilate': 'assimilate', 'Secu-rity.They': 'Security. They',
             # 'ter-HOW': 'terHOW',
             'infra-structure': 'infrastructure', 'recom-mended': 'recommended',
             'Aero-space': 'Aerospace', 'CENT-COM': 'CENTCOM', 'mujahi-deen': 'mujahideen',
             'Encyclo-pedia': 'Encyclopedia',
             # 'millen-434': 'millen434',
             'candi-date': 'candidate',
             'em-ployees': 'employees', 'Afghan-istan': 'Afghanistan', 'Inter-national': 'International',
             'con-nection': 'connection', 'master-mind': 'mastermind', 'wit-nesses': 'witnesses',
             'Des-ignations': 'Designations', 'docu-ments': 'documents', 'recip-ient': 'recipient',
             'Transporta-tion': 'Transportation', 'Immi-gration': 'Immigration', 'Sec-tor': 'Sector',
             'Commission-ers': 'Commissioners', 'Com-FinalNotes': 'ComFinalNotes', 'Per-manent': 'Permanent',
             'inter-views': 'interviews', 'Inspec-tor': 'Inspector', 'Jet-port': 'Jetport',
             'crite-ria.See': 'criteria.See', 'Clau-dia': 'Claudia', 'check-in': 'checkin', 'passen-ger': 'passenger',
             'Sta-tus': 'Status', 'aver-ages': 'averages', 'Explana-tion': 'Explanation',
             'Envi-ronmental': 'Environmental', 'tran-script': 'transcript', 'Account-ing': 'Accounting',
             'simul-taneously': 'simultaneously', 'Con-trol': 'Control', 'col-league': 'colleague',
             'Wood-ward': 'Woodward', 'Gon-zalez': 'Gonzalez', 'Cri-sis': 'Crisis', 'Mul-tiple': 'Multiple',
             'econ-omy': 'economy', 'Poli-castro': 'Policastro', 'fam-ily': 'family', 'Crimi-nal': 'Criminal',
             'DC-8': 'DC8', 'col-NOTES': 'colNOTES', 'respon-sibilities': 'responsibilities', 'Traf-fic': 'Traffic',
             'consid-erably': 'considerably', 'board-ing': 'boarding', 'Jeffer-son': 'Jefferson',
             'sup-plement': 'supplement', 'Lau-ren': 'Lauren', 'Harper-Collins': 'HarperCollins',
             'recipi-ents': 'recipients', 'evi-dence.The': 'evidence.The', '11-Hour': '11Hour',
             'Informa-tion': 'Information', 'assur-ance': 'assurance', 'Exten-sion': 'Extension', '.10-2-6': '.6',
             '.7-1-1': '.1', ',7-1-2': ',2', '.7-4-2': '.2', '.7-1-6': '.6', 'regula-tions': 'regulations',
             '.7-2-3': '.3', 'Eber-hart': 'Eberhart', 'F-15s': 'F15s', 'Acci-dent': 'Accident',
             'Evalua-tion': 'Evaluation', 'thou-sand': 'thousand', 'Comman-der': 'Commander',
             'situa-tion.They': 'situation.They', 'mate-rials': 'materials', 'Air-craft': 'Aircraft',
             'Offi-cer': 'Officer', 'Depart-NOTES': 'DepartNOTES', 'signal-to-noise': 'signal-tonoise',
             'airplane-and': 'airplaneand', 'Obser-vations': 'Observations', 'Emer-gency': 'Emergency',
             'recollec-tion': 'recollection', 'ADA-30': 'ADA30', 'recollec-tions': 'recollections',
             'teleconfer-ence.See': 'teleconference.See', 'Gard-ner': 'Gardner', 'OT-2': 'OT2',
             'coor-dinating': 'coordinating', 'Con-ference': 'Conference', '15-minute': '15minute',
             'Communi-cations': 'Communications', 'con-firm': 'confirm', 'air-borne.The': 'airborne.The',
             'AD-Inspection': 'ADInspection', 'Rah-man': 'Rahman', 'nonvio-lent': 'nonviolent',
             'mid-western': 'midwestern', 'exam-ines': 'examines', 'Arab-and': 'Araband',
             '23.Regard-ing': '23.Regarding', '02-CR': '02CR', 'CR-892': 'CR892', 'Prof-fer': 'Proffer',
             'pseudo-nym': 'pseudonym', 'ana-lytic': 'analytic', '2003-40028CHX': '200340028CHX',
             'Respon-sibilities': 'Responsibilities', 'Afghan-Bosnian': 'AfghanBosnian', 'Con-nection': 'Connection',
             'Par-liament': 'Parliament', 'testi-mony': 'testimony', 'confiden-tial': 'confidential',
             'Activ-ities': 'Activities', '96-30015': '9630015', 'exam-ining': 'examining', 'man-agement': 'management',
             'IA2001-134-HXC': 'IAHXC', 'U.S.Ambas-sador': 'U.S.Ambassador', 'assassina-tion': 'assassination',
             '1559-T': '1559T', 'con-tacts.They': 'contacts.They', 'inter-rogations': 'interrogations',
             'Co-conspirator': 'Coconspirator', 'Malaysian-Indonesian': 'MalaysianIndonesian',
             'Co-Conspira-tor': 'Co-Conspirator', 'interro-gation': 'interrogation', '300A-T': '300AT',
             '1636-T': '1636T', '1602-T': '1602T', '1557C-T': '1557CT', '1557D-T': '1557DT', '1557E-T': '1557ET',
             'Appro-priations': 'Appropriations', 'responsi-bility': 'responsibility', 'Sub-committee': 'Subcommittee',
             'Counterter-rorism': 'Counterterrorism', 'Post-Watergate': 'PostWatergate',
             'Congres-sional': 'Congressional', 'Wat-son': 'Watson', 'Estab-lishment': 'Establishment',
             'num-472': 'num472', 'Sum-mary': 'Summary', 'work-flow': 'workflow', 'I-1': 'I1', 'I-14': 'I14',
             'appen-NOTES': 'appenNOTES', 'Deliv-ery': 'Delivery', 'Ter-rorists': 'Terrorists',
             'Contin-gency': 'Contingency', 'Secu-474': 'Secu474', 'Follow-up': 'Followup', 'Insti-tute': 'Institute',
             'noncoopera-tion': 'noncooperation', 'back-logs': 'backlogs', 'effec-tiveness': 'effectiveness',
             'Gar-vey': 'Garvey', 'Chal-lenges': 'Challenges', 'Avi-ation': 'Aviation', 'Dis-trict': 'District',
             'figur-ing': 'figuring', 'per-mission': 'permission', 'second-ary': 'secondary', 'Car-riers': 'Carriers',
             'Passen-gers': 'Passengers', 'car-rier': 'carrier', 'Gov-ernment': 'Government', 'Pur-suant': 'Pursuant',
             'Schus-ter': 'Schuster', 'Ori-gin': 'Origin', 'Green-wood': 'Greenwood', 'Domes-NOTES': 'DomesNOTES',
             'NSC-39': 'NSC39', 'NSC-62': 'NSC62', 'NSC-63': 'NSC63', 'Protec-tion': 'Protection',
             'Commence-ment': 'Commencement', 'Keep-ing': 'Keeping', 'Col-gate': 'Colgate', 'Inder-furth': 'Inderfurth',
             'subcom-mittee': 'subcommittee', 'War-ren': 'Warren', 'Destruc-tion': 'Destruction',
             'Coun-tering': 'Countering', 'col-laboration': 'collaboration', 'crit-icized': 'criticized',
             'citi-zens': 'citizens', 'sum-mary': 'summary', 'sta-bility': 'stability', 'Oak-ley': 'Oakley',
             'Com-ments': 'Comments', 'Oper-ation': 'Operation', 'Coun-sel': 'Counsel', 'reac-tion': 'reaction',
             'pur-pose': 'purpose', 'Islam-abad': 'Islamabad', 'King-dom': 'Kingdom',
             'non-proliferation': 'nonproliferation', 'Tal-bott': 'Talbott', 'block-ing': 'blocking',
             'Oper-atives': 'Operatives', 'Appre-hension': 'Apprehension', 'evacu-ated': 'evacuated',
             'sub-stance': 'substance', 'Mean-while': 'Meanwhile', 'F-16': 'F16', 'hand-icapping': 'handicapping',
             'Trans-lation': 'Translation', 'accu-rate': 'accurate', 'Back-ground': 'Background', 'Fig-ures': 'Figures',
             'ren-der': 'render', 'Lieu-tenants': 'Lieutenants', 'Cap-ture': 'Capture', 'Execu-tive': 'Executive',
             'Confer-ence': 'Conference', 'esti-mate': 'estimate', 'assas-sinating': 'assassinating',
             'inter-rogation': 'interrogation', 'contin-ued': 'continued', 'under-wrote': 'underwrote',
             'inter-rogation.Contrary': 'interrogation.Contrary', 'man-ufactured': 'manufactured',
             'a9/11-type': 'atype', 'loca-tion': 'location', 'missile-smuggling': 'missilesmuggling',
             'Zubay-dah': 'Zubaydah', 'Lim-burg': 'Limburg', '.-trained': '.trained', 'B-1': 'B1',
             'pro-cure': 'procure', 'split-ting': 'splitting', 'Thai-land': 'Thailand', 'for9/11-related': 'forrelated',
             'descrip-tion': 'description', '265A-NY': '265ANY', 'NY-280350': 'NY280350', 'doctor-ing': 'doctoring',
             'subse-quent': 'subsequent', '280350-CG': '280350CG', 'one-bedroom': 'onebedroom',
             'on9/11-related': 'onrelated', 'dis-cover': 'discover', 'Zam-mar': 'Zammar', 'encourag-ing': 'encouraging',
             'Marien-strasse': 'Marienstrasse', 'Palestin-ian': 'Palestinian', '280350-BN': '280350BN',
             'BN-415': 'BN415', 'wit-ness': 'witness', '15-year': '15year', 'sen-tence': 'sentence',
             'Internet.Accord-ing': 'Internet.According', 'Pros-ecutor': 'Prosecutor', 'Sen-tencing': 'Sentencing',
             'han-dle': 'handle', 'tran-siting': 'transiting', 'over-lay': 'overlay', 'Inves-tigation': 'Investigation',
             'celebra-tion': 'celebration', 'behav-ior': 'behavior', 'Investi-496': 'Investi496',
             'interroga-tion': 'interrogation', 'schools.Accord-ing': 'schools.According', 'Meet-NOTES': 'MeetNOTES',
             'Mil-itants': 'Militants', '2002-30060CH': '200230060CH', '.-based': '.based', 'recipi-ent': 'recipient',
             'offset-ting': 'offsetting', 'Laun-dering': 'Laundering', '2002-30138H': '200230138H',
             'terror-498': 'terror498', 'indi-cates': 'indicates', 'Dia-monds': 'Diamonds',
             'approx-imately': 'approximately', 'chem-ical': 'chemical', 'mil-lennial': 'millennial',
             'Boua-bide': 'Bouabide', 'techni-cal': 'technical', 'entt-bomb': 'enttbomb', 'Gham-chi': 'Ghamchi',
             'prece-500': 'prece500', 'Terror-ism': 'Terrorism', 'pass-ports': 'passports', 'CR99-666C': 'CR99666C',
             'under-lined': 'underlined', 'Pro-cedure': 'Procedure', 'Asso-ciate': 'Associate', 'al-Midhar': 'alMidhar',
             'trav-eling': 'traveling', 'depar-ture': 'departure', 'After-Action': 'AfterAction',
             'Perspec-tive': 'Perspective', 'sup-plemental': 'supplemental', 'supple-NOTES': 'suppleNOTES',
             'unre-solved': 'unresolved', 'launder-ing': 'laundering', 'iner-tia': 'inertia', 'PDD-62': 'PDD62',
             'PDD-39': 'PDD39', 'Millen-nium': 'Millennium', 'Extrem-ist': 'Extremist', 'J-39': 'J39',
             'iden-tified': 'identified', 'sil-ver': 'silver', 'leader-ship': 'leadership', 'al-Badawi': 'alBadawi',
             'Bod-ine': 'Bodine', 'character-ization': 'characterization', 'communica-tion': 'communication',
             'pho-tograph': 'photograph', 'Moham-mad': 'Mohammad', 'admin-NOTES': 'adminNOTES', 'Infi-nite': 'Infinite',
             'East-ham': 'Eastham', 'objec-tion': 'objection', 'cir-cumstances': 'circumstances', 'Pres-508': 'Pres508',
             'Pol-icy': 'Policy', 'cap-tors': 'captors', 'Princi-pals': 'Principals', 'Net-works': 'Networks',
             'For-eign': 'Foreign', '.-Taliban': '.Taliban', 'Meet-ing': 'Meeting',
             'Qida-Afghan-Pakistan': 'Qida-AfghanPakistan', 'Conclu-sions': 'Conclusions', 'Minis-ter': 'Minister',
             'Con-clusions': 'Conclusions', 'Strate-gic': 'Strategic', 'Subcom-mittee': 'Subcommittee',
             'func-tions': 'functions', 'applica-tion': 'application', 'con-stitutionality': 'constitutionality',
             'mod-ifications': 'modifications', 'Talk-ing': 'Talking', 'oppo-sition': 'opposition',
             'docu-ment': 'document', 'ital-icized': 'italicized', 'pur-suing': 'pursuing',
             'exclu-sively': 'exclusively', 'satis-factory': 'satisfactory', 'Sur-rounded': 'Surrounded',
             'addi-tion': 'addition', 'Thu-mairy': 'Thumairy', 'refus-ing': 'refusing', 'Mekhe-mar': 'Mekhemar',
             'follow-ers': 'followers', 'Benom-rane': 'Benomrane', 'intro-duced': 'introduced',
             'still-unidentified': 'stillunidentified', 'pray-ing': 'praying', 'inter-viewed': 'interviewed',
             'denial.Accord-ing': 'denial.According', 'wel-come': 'welcome', 'furnish-ings': 'furnishings',
             '280350-SD': '280350SD', 'sus-pected': 'suspected', 'elec-tronic': 'electronic', 'rais-ing': 'raising',
             'min-istry': 'ministry', 'conduct.Thu-mairy': 'conduct.Thumairy', 'house-mate': 'housemate',
             'acquain-tances': 'acquaintances', 'Time-line': 'Timeline', '280350-PR': '280350PR',
             '280350-NK': '280350NK', 'NY-280350-302': 'NY280350-302', '.01-455-A': '.A', '280350-TP': '280350TP',
             'TP-5382': 'TP5382', '280350-CE': '280350CE', 'TP-5679': 'TP5679', 'NY-280350-302-': 'NY280350-302-',
             '-280350-302-16752': '-16752', 'CE-624': 'CE624', 'FD-302': 'FD302', 'with-drawn': 'withdrawn',
             'documenta-tion': 'documentation', 'leav-ing': 'leaving', '-280350-302-7134': '-7134',
             'Pentt-bom': 'Penttbom', '280350-PX': '280350PX', '265A-NT': '265ANT', 'NT-280350': 'NT280350',
             '280350-SF': '280350SF', '280350-IN': '280350IN', 'NY-280530': 'NY280530', '280530-IN': '280530IN',
             'mem-orandum': 'memorandum', 'I-94': 'I94', 'spir-itual': 'spiritual', 'per-severance': 'perseverance',
             '280350-W': '280350W', '280350-OC': '280350OC', '280350-NH': '280350NH', '265A-280350': '265A280350',
             'NY-280350-302-9715': 'NY9715', 'NY-280350-302-2340': 'NY2340', '265D-NY': '265DNY',
             '280350-OUT': '280350OUT', 'Moroc-can': 'Moroccan', 'Fed-eral': 'Federal', 'BN-98': 'BN98',
             'NY-280350-302-615': 'NY615', '280350-MM': '280350MM', '280350-AT': '280350AT', 'AT-141': 'AT141',
             '280350-NF': '280350NF', 'NF-48': 'NF48', '65A-NY': '65ANY', 'NY-280350-302-615,688': 'NY615,688',
             'attrib-uted': 'attributed', 'seri-als': 'serials', '280350-FD': '280350FD', 'NY-NOTES': 'NYNOTES',
             'cit-ing': 'citing', 'time-line': 'timeline', 'Immigra-tion': 'Immigration', 'acknowl-524': 'acknowl524',
             '55.Accord-ing': '55.According', 'reen-tered': 'reentered', 'Haz-nawi': 'Haznawi', 'Ban-dar': 'Bandar',
             'Pakistan-Afghanistan': 'PakistanAfghanistan', 'vis-iting': 'visiting', 'broth-ers': 'brothers',
             'col-lege': 'college', 'video-tape': 'videotape', 'doc-uments': 'documents', 'one-month': 'onemonth',
             '315N-NY': '315NNY', 'NY-280359': 'NY280359', '280359-RY': '280359RY', '280350-DL': '280350DL',
             '280350-A': '280350A', 'MM-302': 'MM302', '280350-RY': '280350RY',
             'apartment.Post-9/11': 'apartment.Post9/11', 'apart-ments': 'apartments', 'NY-280350-302-19615': 'NY19615',
             '280350-MM-Sub': '280350MM-Sub', '280350-HQ': '280350HQ', 'appli-cation': 'application',
             '2004-40009HCX': '200440009HCX', 'Pent-tbom': 'Penttbom', '280350-F': '280350F',
             'inconclu-sive': 'inconclusive', '280350-BS': '280350BS', 'accept-able': 'acceptable',
             'com-plicity': 'complicity', '280350-LV': '280350LV', 'interro-gations': 'interrogations',
             'Ess-abar': 'Essabar', '280350-WF': '280350WF', '280350-BA': '280350BA', '280350-532': '280350532',
             '280350-CD': '280350CD', '280350-302': '280350302', '280350-LO': '280350LO', 'respec-tive': 'respective',
             'docu-ments.The': 'documents.The', 'U.S.Ter-rorism': 'U.S.Terrorism', 'inves-tigated': 'investigated',
             'citi-zenship': 'citizenship', 'room-mate': 'roommate', '266A-NY': '266ANY', 'NY-279198': 'NY279198',
             'Fun-damentalist': 'Fundamentalist', 'Eliminat-ing': 'Eliminating', 'secu-NOTES': 'secuNOTES',
             '108-00': '10800', 'circu-lars': 'circulars', 'IC-2001': 'IC2001', '2001-04A': '200104A',
             'coun-terterrorism.We': 'counterterrorism.We', 'Bow-man': 'Bowman', 'Retrospec-tive': 'Retrospective',
             'Inspec-536': 'Inspec536', 'overabun-dance': 'overabundance', 'war-rant': 'warrant', 'pro-viso': 'proviso',
             'Hay-den': 'Hayden', 'regard-ing': 'regarding', 'watch-list': 'watchlist', 'attach-ment': 'attachment',
             'suf-ficient': 'sufficient', 'wel-ter': 'welter', 'pur-suant': 'pursuant', 'permit-ted': 'permitted',
             'read-ily': 'readily', 'trans-actions': 'transactions', 'com-bined': 'combined', 'rat-ing': 'rating',
             '199M-MP': '199MMP', 'MP-60130': 'MP60130', 'can-celled': 'cancelled', 'identi-fication': 'identification',
             '14-inch-wide': '14inch-wide', 'ele-vators': 'elevators', 'Mag-azine': 'Magazine',
             'Pro-cedures': 'Procedures', '12-hour': '12hour', 'intra-and': 'intraand', 'inter-agency': 'interagency',
             'pro-vided.The': 'provided.The', 'pro-cedure': 'procedure', 'Civil-ian': 'Civilian',
             'announce-ment': 'announcement', 'hel-icopters': 'helicopters', 'reg-ulations': 'regulations',
             'offi-NOTES': 'offiNOTES', 'H-41': 'H41', 'tran-scripts': 'transcripts', 'Bat-talion': 'Battalion',
             'fire-houses': 'firehouses', 'activat-ing': 'activating', 'record-ing': 'recording',
             'Battal-ion': 'Battalion', 'perspec-tive': 'perspective', 'heli-copter': 'helicopter',
             'Adminis-trative': 'Administrative', 'trans-missions': 'transmissions', 'Chan-nel': 'Channel',
             'depart-mental': 'departmental', 'Lin-coln': 'Lincoln', 'A-20': 'A20', 'A-21': 'A21',
             'disposi-tion': 'disposition', 'B-12': 'B12', 'B-15': 'B15', 'A-4': 'A4', 'C-26': 'C26',
             'Arling-ton': 'Arlington', 'A-30': 'A30', 'A-31': 'A31', 'died.Twenty-six': 'died.Twentysix',
             'con-ditions': 'conditions', 'Comman-ders.Terrorist': 'Commanders.Terrorist', 'Haz-mat': 'Hazmat',
             'never-theless': 'nevertheless', '29-minute': '29minute', 'dissemi-nated': 'disseminated',
             'morn-ing': 'morning', 'after-noon': 'afternoon', 'Deb-orah': 'Deborah', 'confer-ees': 'conferees',
             'mat-ter': 'matter', 'Cam-bone': 'Cambone', 'impre-cise': 'imprecise', 'col-lected': 'collected',
             'Improve-ment': 'Improvement', 'associ-ate': 'associate', 'con-sistent': 'consistent',
             'News-day': 'Newsday', 'Whit-man': 'Whitman', 'coor-dinated': 'coordinated', 'num-bers': 'numbers',
             'Ken-tucky': 'Kentucky', 'direct-ing': 'directing', 'Terror-ist': 'Terrorist', 'Sup-port': 'Support',
             'man-ner': 'manner', 'delib-NOTES': 'delibNOTES', 'Esti-mate': 'Estimate', 'McGraw-Hill': 'McGrawHill',
             'pos-sess': 'possess', 'Hijack-ing': 'Hijacking', '34-page': '34page', 'Consid-erations': 'Considerations',
             'www.white-house.gov/news/releases/2003/02/20030214-7.html': 'www.whitehouse.gov/news/releases/2003/02/20030214-7.html',
             'millen-nium': 'millennium', 'believ-ers': 'believers', 'peo-ple.They': 'people.They',
             'for-ever': 'forever', 'Sum-mit': 'Summit', 'Indi-vidual': 'Individual', 'Establish-ing': 'Establishing',
             'Occi-dentalism': 'Occidentalism', 'athttp://english.daralhayat.com/Spec/02-2004': 'at2004',
             'Article-2004021': 'Article2004021', '3-ac40bdaf': '3ac40bdaf', 'ac40bdaf-c0a8': 'ac40bdafc0a8',
             'c0a8-01ed': 'c0a801ed', '01ed-004e': '01ed004e', '004e-5e7ac897d678': '004e5e7ac897d678',
             'Non-proliferation': 'Nonproliferation', 'Heart-land': 'Heartland', 'watch-listed.Had': 'watchlisted.Had',
             'fraud-ulent': 'fraudulent', 'incorpo-rating': 'incorporating', 'bio-metric': 'biometric',
             'docu-ments.Pub.L.No': 'documents.Pub.L.No', 'nation-als': 'nationals', 'law-fulness': 'lawfulness',
             'Stu-dents': 'Students', 'per-564': 'per564', 'Initia-tive': 'Initiative', 'let-ter': 'letter',
             'task-ing': 'tasking', 'super-vise': 'supervise', 'retain-ing': 'retaining', 'assem-bled': 'assembled',
             'com-mands': 'commands', 'opera-tional': 'operational', 'Stan-ford': 'Stanford', 'Augus-tine': 'Augustine',
             'Aware-ness': 'Awareness'}

    examples = set()
    fix_candidates = dict()
    running_count = 0
    for index_sentence, sentence in enumerate(sentences):
        words = casual_tokenize(sentence)
        for index, word in enumerate(words):
            if word.endswith('-'):
                running_count += 1
                example = words[index - 1] + word + words[index + 1]
                fix_candidates[example] = words[index - 1] + words[index + 1]
                if example in fixes.keys():
                    print('{}: {} : {} :: {}'.format(index_sentence, running_count, example, fixes[example]))
                else:
                    print('{}: {} : {}'.format(index_sentence, running_count, example))

                examples.add(example)
    print('we found {} distinct splits'.format(len(examples)))
    print(fix_candidates)
    modified = list()
    for index_sentence, sentence in enumerate(sentences):
        words = word_tokenize(sentence)
        fixed_words = fix(words)
        modified.append(' '.join(fixed_words))
    sentences = modified

    # now we need to count words and do a frequency score for each word
    freq_dist = FreqDist()
    for sentence in sentences:
        for word in word_tokenize(sentence):
            freq_dist[word.lower()] += 1

    word_count = freq_dist.N()
    print('our frequency distribution has {} items'.format(len(freq_dist)))
    print('our word count is {}'.format(word_count))

    # now let's traverse our frequency distribution and build our token-probability map
    probabilities = {word: float(freq_dist[word]) / float(word_count) for word in freq_dist}

    # now we are ready to calculate scores for each sentence
    sentence_scores = {
        sentence: (sum([probabilities[word.lower()] for word in word_tokenize(sentence)]), index)
        for index, sentence in enumerate(sentences)}

    candidates = {key: value for key, value in sentence_scores.items() if value[0] > 3.0}

    for key, value in candidates.items():
        print('{:5.2f} {} {}'.format(value[0], value[1], key.replace('\n', ' ')))

    values = [value for value in candidates.values()]
    plt.plot(sorted(values), 'o', mfc='none')
    output_file = './output/first_cut_plot.png'
    print('writing score plot to {}'.format(output_file))
    plt.savefig(output_file)
    print('total elapsed time: {:5.2f}s'.format(time() - time_start))
