# -*- coding: utf-8 -*-
"""
Created on Mon Apr  1 12:13:06 2019

@author: mikedelong
"""

from collections import OrderedDict
from json import load
from os.path import exists
from time import time

import matplotlib.pyplot as plt
from nltk import FreqDist
from nltk import word_tokenize
from nltk.tokenize import casual_tokenize
from nltk.tokenize import sent_tokenize
from tika import parser


def fix(arg):
    result = list()
    skip = False
    for item_index, item in enumerate(arg):
        if item.endswith('-'):
            out_item = item[:-1]
            result.append(out_item + arg[item_index + 1])
            skip = True
        else:
            if skip:
                skip = False
            else:
                result.append(item)
    return result


settings_file = 'first_cut.json'
if __name__ == '__main__':
    time_start = time()
    with open(settings_file, 'r') as settings_fp:
        settings = load(settings_fp)

    input_folder = settings['input_folder'] if \
        'input_folder' in settings.keys() else None
    if input_folder is not None:
        if not exists(input_folder):
            print('input data folder does not exist. Quitting.')
            quit(-1)
    else:
        print('input folder name is missing from settings. Quitting.')
        quit(-1)

    input_file = settings['input_file'] if 'input_file' in settings.keys() else None
    full_input_file = None
    if input_file is not None:
        full_input_file = input_folder + input_file if input_folder.endswith('/') else input_folder + '/' + input_file
    else:
        print('input file name is missing from settings. Quitting.')
        quit(-1)

    if not exists(full_input_file):
        print('input file {} is missing. Quitting.'.format(full_input_file))
        quit(-1)

    parsed = parser.from_file(full_input_file)

    print('our content is a string of length {}'.format(len(parsed['content'])))
    content = parsed['content']

    # todo fix quotes
    # todo put summary sentences back in order
    # todo move fixes to data
    sentences = sent_tokenize(content, language='english')

    print('before we remove very short sentences we have {} sentences'.format(len(sentences)))
    sentences = [item for item in sentences if len(item) > 1]
    print('after we remove very short sentences we have {} sentences'.format(len(sentences)))

    fixes = {'.-Pakistani': '.Pakistani', '.-bound': '.bound', '.-flagged': '.flagged', '00.Cap-tain': '00. Captain',
             '108-00': '10800', '1559-T': '1559T', '16-acre': '16acre', '16-room': '16room',
             '1946.Fire-fighter': '1946. Firefighter', '2000.Ham-bali': '2000. Hambali',
             '23.Regard-ing': '23. Regarding', '280350-302': '280350302', '280350-CD': '280350CD',
             '280350-LO': '280350LO', 'Abdul-lah': 'Abdullah', 'Acci-dent': 'Accident', 'Account-ing': 'Accounting',
             'Activ-ities': 'Activities', 'Addi-tionally': 'Additionally', 'Admi-ral': 'Admiral',
             'Admin-istration': 'Administration', 'Adminis-trative': 'Administrative', 'Aero-space': 'Aerospace',
             'Afghan-istan': 'Afghanistan', 'After-Action': 'AfterAction', 'Air-craft': 'Aircraft',
             'Air-lines': 'Airlines', 'Air-port': 'Airport', 'Amer-ica': 'America', 'Amer-ican': 'American',
             'Amer-icans': 'Americans', 'Ameri-can': 'American', 'Ameri-cans': 'Americans', 'Analy-sis': 'Analysis',
             'Ange-les': 'Angeles', 'Angle-ton': 'Angleton', 'Appre-hension': 'Apprehension',
             'Appro-priations': 'Appropriations', 'Ara-bia': 'Arabia', 'Ara-bian': 'Arabian', 'Ara-bic': 'Arabic',
             'Arab-and': 'Araband', 'Arabia.Khal-lad': 'Arabia. Khallad', 'Ari-zona': 'Arizona',
             'Arling-ton': 'Arlington', 'Assis-tance': 'Assistance', 'Asso-ciate': 'Associate', 'Attor-ney': 'Attorney',
             'Augus-tine': 'Augustine', 'Author-ity': 'Authority', 'Avi-ation': 'Aviation', 'Avia-tion': 'Aviation',
             'Aware-ness': 'Awareness', 'Back-ground': 'Background', 'Bakar-bashat': 'Bakarbashat', 'Ban-dar': 'Bandar',
             'Ban-shiri': 'Banshiri', 'Baniham-mad': 'Banihammad', 'Bar-bara': 'Barbara', 'Bat-talion': 'Battalion',
             'Battal-ion': 'Battalion', 'Bay-oumi': 'Bayoumi', 'Benom-rane': 'Benomrane', 'Binal-shibh': 'Binalshibh',
             'Bod-ine': 'Bodine', 'Boua-bide': 'Bouabide', 'Bow-man': 'Bowman', 'Brook-lyn': 'Brooklyn',
             'Bud-get': 'Budget', 'CENT-COM': 'CENTCOM', 'Cal-ifornia': 'California', 'Califor-nia': 'California',
             'Cam-bone': 'Cambone', 'Cana-dian': 'Canadian', 'Cap-tain': 'Captain', 'Cap-ture': 'Capture',
             'Car-ney': 'Carney', 'Car-olina': 'Carolina', 'Car-riers': 'Carriers', 'Cen-ter': 'Center',
             'Cen-tral': 'Central', 'Chair-man': 'Chairman', 'Chal-lenges': 'Challenges', 'Chan-nel': 'Channel',
             'Chech-nya': 'Chechnya', 'Civil-ian': 'Civilian', 'Clau-dia': 'Claudia', 'Clin-ton': 'Clinton',
             'Co-Conspira-tor': 'Co-Conspirator', 'Col-gate': 'Colgate', 'Col-lection': 'Collection',
             'Com-mand': 'Command', 'Com-ments': 'Comments', 'Com-mission': 'Commission', 'Com-mittee': 'Committee',
             'Comman-der': 'Commander', 'Comman-ders.Terrorist': 'Commanders. Terrorist',
             'Commence-ment': 'Commencement', 'Comment-ing': 'Commenting', 'Commis-sion': 'Commission',
             'Commission-ers': 'Commissioners', 'Commit-tee': 'Committee', 'Communi-cations': 'Communications',
             'Con-clusions': 'Conclusions', 'Con-dition': 'Condition', 'Con-ference': 'Conference',
             'Con-gress': 'Congress', 'Con-nection': 'Connection', 'Con-tra': 'Contra', 'Con-trol': 'Control',
             'Con-trollers': 'Controllers', 'Con-vention': 'Convention', 'Conclu-sions': 'Conclusions',
             'Confer-ence': 'Conference', 'Congres-sional': 'Congressional', 'Consid-erations': 'Considerations',
             'Contin-gency': 'Contingency', 'Controver-sies': 'Controversies', 'Coun-cil': 'Council',
             'Coun-sel': 'Counsel', 'Coun-tering': 'Countering', 'Coun-terintelligence': 'Counterintelligence',
             'Coun-terterrorism': 'Counterterrorism', 'Counterin-telligence': 'Counterintelligence',
             'Counterintelli-gence': 'Counterintelligence', 'Countert-errorist': 'Counterterrorist',
             'Counterter-rorism': 'Counterterrorism', 'Counterter-rorist': 'Counterterrorist', 'Cri-sis': 'Crisis',
             'Crimi-nal': 'Criminal', 'DCI.Pres-ident': 'DCI. President', 'Dam-age': 'Damage', 'Deb-orah': 'Deborah',
             'Decem-ber': 'December', 'Deliv-ery': 'Delivery', 'Depart-ment': 'Department',
             'Des-ignations': 'Designations', 'Destruc-tion': 'Destruction', 'Develop-ment': 'Development',
             'Dia-monds': 'Diamonds', 'Direc-tor': 'Director', 'Dis-covering': 'Discovering', 'Dis-trict': 'District',
             'Divi-sion': 'Division', 'Dono-van': 'Donovan', 'East-erners': 'Easterners', 'East-ham': 'Eastham',
             'Eber-hart': 'Eberhart', 'Econ-omist': 'Economist', 'Egypt-ian': 'Egyptian', 'Eliminat-ing': 'Eliminating',
             'Embold-ened': 'Emboldened', 'Emer-gency': 'Emergency', 'Emergen-cies': 'Emergencies',
             'Emi-rates': 'Emirates', 'Emi-rati': 'Emirati', 'Encyclo-pedia': 'Encyclopedia', 'Eng-lish': 'English',
             'Envi-ronmental': 'Environmental', 'Ess-abar': 'Essabar', 'Estab-lishment': 'Establishment',
             'Establish-ing': 'Establishing', 'Esti-mate': 'Estimate', 'Evad-ing': 'Evading',
             'Evalua-tion': 'Evaluation', 'Evi-dence': 'Evidence', 'Exec-utive': 'Executive', 'Execu-tive': 'Executive',
             'Explana-tion': 'Explanation', 'Exten-sion': 'Extension', 'Extrem-ist': 'Extremist', 'F-16': 'F16',
             'Fair-fax': 'Fairfax', 'Feb-ruary': 'February', 'Febru-ary': 'February', 'Fed-eral': 'Federal',
             'Fig-ures': 'Figures', 'Finan-cial': 'Financial', 'Fluores-cent': 'Fluorescent', 'Fol-lowing': 'Following',
             'Follow-up': 'Followup', 'For-eign': 'Foreign', 'Fran-cisco': 'Francisco',
             'Fun-damentalist': 'Fundamentalist', 'Fur-thermore': 'Furthermore', 'Gar-vey': 'Garvey',
             'Gard-ner': 'Gardner', 'Gen-eral': 'General', 'Ger-man': 'German', 'Ger-many': 'Germany',
             'Ger-many.There': 'Germany. There', 'Gham-chi': 'Ghamchi', 'Gon-zalez': 'Gonzalez',
             'Gov-ernment': 'Government', 'Gover-nors': 'Governors', 'Green-wood': 'Greenwood', 'Ham-bali': 'Hambali',
             'Hambali.Ham-bali': 'Hambali. Hambali', 'Han-jour': 'Hanjour', 'Hay-den': 'Hayden', 'Haz-mat': 'Hazmat',
             'Haz-nawi': 'Haznawi', 'Head-ing': 'Heading', 'Heart-land': 'Heartland', 'Hern-don': 'Herndon',
             'Hezbol-lah': 'Hezbollah', 'Hijack-ing': 'Hijacking', 'Hizbul-Ittihad': 'HizbulIttihad',
             'Home-land': 'Homeland', 'Hort-man': 'Hortman', 'House.Amer-ican': 'House. American',
             'How-ever': 'However', 'Hus-sein': 'Hussein', 'I.Western-educated': 'I. Westerneducated',
             'Immi-grant': 'Immigrant', 'Immi-gration': 'Immigration', 'Immigra-tion': 'Immigration',
             'Improve-ment': 'Improvement', 'Inder-furth': 'Inderfurth', 'Indi-anapolis': 'Indianapolis',
             'Indi-vidual': 'Individual', 'Infi-nite': 'Infinite', 'Infor-mation': 'Information',
             'Informa-tion': 'Information', 'Initia-tive': 'Initiative', 'Inspec-tor': 'Inspector',
             'Inspec-tors': 'Inspectors', 'Insti-tute': 'Institute', 'Inte-gration': 'Integration',
             'Intel-ligence': 'Intelligence', 'Intel-ligence.The': 'Intelligence. The', 'Intelli-gence': 'Intelligence',
             'Inter-Services': 'InterServices', 'Inter-national': 'International', 'Inter-net': 'Internet',
             'Internet.Accord-ing': 'Internet. According', 'Inves-tigation': 'Investigation',
             'Investiga-tion': 'Investigation', 'Invok-ing': 'Invoking', 'Islam-abad': 'Islamabad',
             'Jan-uary': 'January', 'Janu-ary': 'January', 'Jar-rah': 'Jarrah', 'Jeffer-son': 'Jefferson',
             'Jer-sey.As': 'Jersey. As', 'Jet-port': 'Jetport', 'Jor-dan': 'Jordan', 'Jor-danian': 'Jordanian',
             'Jus-tice': 'Justice', 'Kah-tani': 'Kahtani', 'Kah-tani.Upon': 'Kahtani. Upon', 'Kan-dahar': 'Kandahar',
             'Kanda-har': 'Kandahar', 'Kanda-har.KSM': 'Kandahar. KSM', 'Kanda-har.The': 'Kandahar. The',
             'Kanda-har.Though': 'Kandahar. Though', 'Kash-mir': 'Kashmir', 'Keep-ing': 'Keeping',
             'Ken-tucky': 'Kentucky', 'Khal-dan': 'Khaldan', 'Khal-lad': 'Khallad', 'Khal-lam': 'Khallam',
             'Khar-toum': 'Khartoum', 'Kho-bar': 'Khobar', 'King-dom': 'Kingdom', 'Lan-gley': 'Langley',
             'Lang-ley': 'Langley', 'Lau-ren': 'Lauren', 'Laun-dering': 'Laundering', 'Lib-erty': 'Liberty',
             'Lieu-tenants': 'Lieutenants', 'Lim-burg': 'Limburg', 'Lin-coln': 'Lincoln', 'Lon-don': 'London',
             'Mag-azine': 'Magazine', 'Man-agement': 'Management', 'Man-agers': 'Managers', 'Manage-ment': 'Management',
             'Manhat-tan': 'Manhattan', 'Marien-strasse': 'Marienstrasse', 'Mary-land': 'Maryland',
             'Mas-soud': 'Massoud', 'Mass-achusetts': 'Massachusetts', 'Mauri-tanian': 'Mauritanian',
             'McLaugh-lin': 'McLaughlin', 'Mean-while': 'Meanwhile', 'Meet-ing': 'Meeting', 'Mekhe-mar': 'Mekhemar',
             'Memoran-dum': 'Memorandum', 'Mexicans.Cur-rently': 'Mexicans. Currently', 'Mid-dle': 'Middle',
             'Mih-dhar': 'Mihdhar', 'Mihd-har': 'Mihdhar', 'Mihd-har.Two': 'Mihdhar. Two', 'Mil-itants': 'Militants',
             'Mil-itary': 'Military', 'Millen-nium': 'Millennium', 'Min-ister': 'Minister',
             'Min-neapolis': 'Minneapolis', 'Minis-ter': 'Minister', 'Moham-mad': 'Mohammad', 'Mon-treal': 'Montreal',
             'Moroc-can': 'Moroccan', 'Motas-sadeq': 'Motassadeq', 'Mous-saoui': 'Moussaoui', 'Mul-lah': 'Mullah',
             'Mul-tiple': 'Multiple', 'Mus-lim': 'Muslim', 'Mus-lims': 'Muslims', 'Mushar-raf': 'Musharraf',
             'Nei-ther': 'Neither', 'Net-works': 'Networks', 'Never-theless': 'Nevertheless',
             'Non-proliferation': 'Nonproliferation', 'Nor-man': 'Norman', 'North-ern': 'Northern', 'Not-ing': 'Noting',
             'Notifica-tion': 'Notification', 'Novem-ber': 'November', 'Oak-ley': 'Oakley',
             'Obser-vations': 'Observations', 'Occi-dentalism': 'Occidentalism', 'Octo-ber': 'October',
             'Offi-cer': 'Officer', 'Oper-ation': 'Operation', 'Oper-ations': 'Operations', 'Oper-atives': 'Operatives',
             'Opera-tions': 'Operations', 'Orga-nization': 'Organization', 'Ori-gin': 'Origin', 'Over-all': 'Overall',
             'Pak-istan': 'Pakistan', 'Pak-istan.The': 'Pakistan. The', 'Pak-istani': 'Pakistani',
             'Pales-tine': 'Palestine', 'Palestin-ian': 'Palestinian', 'Par-liament': 'Parliament',
             'Pash-tun': 'Pashtun', 'Passen-ger': 'Passenger', 'Passen-gers': 'Passengers', 'Pen-tagon': 'Pentagon',
             'Penn-sylvania': 'Pennsylvania', 'Pent-tbom': 'PENTTBOM', 'Penta-gon': 'Pentagon', 'Pentt-bom': 'Penttbom',
             'Per-manent': 'Permanent', 'Per-vez': 'Pervez', 'Perspec-tive': 'Perspective', 'Philip-pine': 'Philippine',
             'Philip-pines': 'Philippines', 'Plan-ning': 'Planning', 'Pol-icy': 'Policy', 'Poli-castro': 'Policastro',
             'Pop-ular': 'Popular', 'Post-Watergate': 'PostWatergate', 'Pre-sumably': 'Presumably',
             'Pre-venting': 'Preventing', 'Preda-tor': 'Predator', 'Prepared-ness': 'Preparedness',
             'Pres-ident': 'President', 'Presi-dent': 'President', 'Presi-dential': 'Presidential',
             'Presiden-tial': 'Presidential', 'Prin-cipals': 'Principals', 'Princi-pals': 'Principals',
             'Private-sec-tor': 'Private-sector', 'Pro-cedure': 'Procedure', 'Pro-cedures': 'Procedures',
             'Pro-gram': 'Program', 'Pro-tection': 'Protection', 'Prof-fer': 'Proffer', 'Pros-ecutor': 'Prosecutor',
             'Protec-tion': 'Protection', 'Pur-suant': 'Pursuant', 'Rah-man': 'Rahman', 'Rea-gan': 'Reagan',
             'Recogniz-ing': 'Recognizing', 'Regard-ing': 'Regarding', 'Representa-tives': 'Representatives',
             'Repub-lic': 'Republic', 'Respon-sibilities': 'Responsibilities', 'Respon-sibility': 'Responsibility',
             'Responsi-bilities': 'Responsibilities', 'Retrospec-tive': 'Retrospective', 'Revolu-tion': 'Revolution',
             'Rums-feld': 'Rumsfeld', 'Rus-sia': 'Russia', 'Sad-dam': 'Saddam',
             'Salem.Working-level': 'Salem. Working-level', 'Schus-ter': 'Schuster', 'Sec-retary': 'Secretary',
             'Sec-tor': 'Sector', 'Secre-tary': 'Secretary', 'Secu-474': 'Secu474', 'Secu-rity': 'Security',
             'Secu-rity.They': 'Security. They', 'Sen-tencing': 'Sentencing', 'Sep-tember': 'September',
             'Septem-ber': 'September', 'Ser-bia': 'Serbia', 'Ser-vice': 'Service',
             'Service.Dur-ing': 'Service. During', 'She-hhi': 'Shehhi', 'Sheh-hi': 'Shehhi', 'Shel-ton': 'Shelton',
             'Sim-ilarly': 'Similarly', 'Sit-uation': 'Situation', 'South-ern': 'Southern', 'Spe-cial': 'Special',
             'Sta-tus': 'Status', 'Stan-ford': 'Stanford', 'Strate-gic': 'Strategic', 'Stu-dents': 'Students',
             'Sub-committee': 'Subcommittee', 'Subcom-mittee': 'Subcommittee', 'Sum-mit': 'Summit',
             'Sup-port': 'Support', 'Superin-tendent': 'Superintendent', 'Sur-rounded': 'Surrounded',
             'Sus-picion': 'Suspicion', 'Tajik-istan': 'Tajikistan', 'Tal-bott': 'Talbott', 'Tal-iban': 'Taliban',
             'Tali-ban': 'Taliban', 'Talk-ing': 'Talking', 'Ter-rorism': 'Terrorism', 'Ter-rorist': 'Terrorist',
             'Ter-rorists': 'Terrorists', 'Terror-ism': 'Terrorism', 'Terror-ist': 'Terrorist', 'Thai-land': 'Thailand',
             'The11:000-member': 'The 1:000-member', 'The40:000-officer': 'The 40:000-officer', 'Thu-mairy': 'Thumairy',
             'Time-line': 'Timeline', 'Tom-ahawk': 'Tomahawk', 'Traf-fic': 'Traffic', 'Trans-lation': 'Translation',
             'Trans-portation': 'Transportation', 'Transporta-tion': 'Transportation', 'Trea-sury': 'Treasury',
             'U.S.Ambas-sador': 'U.S. Ambassador', 'U.S.Attor-ney': 'U.S. Attorney', 'U.S.Ter-rorism': 'U.S. Terrorism',
             'U.S.gov-ernment': 'U.S. government', 'Usu-ally': 'Usually', 'Vic-toria': 'Victoria',
             'Vine-yard': 'Vineyard', 'Vir-ginia': 'Virginia', 'Vir-ginia.As': 'Virginia. As', 'Wah-habi': 'Wahhabi',
             'War-ren': 'Warren', 'Wash-ington': 'Washington', 'Washing-ton': 'Washington', 'Wat-son': 'Watson',
             'West-ern': 'Western', 'Whit-man': 'Whitman', 'Wol-fowitz': 'Wolfowitz', 'Wood-ward': 'Woodward',
             'Zam-mar': 'Zammar', 'Zubay-dah': 'Zubaydah', 'a1:500-pound': 'a 1:500-pound',
             'a9/11-scale': 'a 9/11-scale', 'a9/11-type': 'a 9/11-type', 'aban-don': 'abandon', 'abil-ity': 'ability',
             'accept-able': 'acceptable', 'acci-dent': 'accident', 'accom-panying': 'accompanying',
             'accom-plish': 'accomplish', 'accommo-date': 'accommodate', 'accor-dance': 'accordance',
             'accord-ing': 'according', 'accu-rate': 'accurate', 'accus-tomed': 'accustomed', 'achiev-ing': 'achieving',
             'acknowl-edged': 'acknowledged', 'acquain-tance': 'acquaintance', 'acquain-tances': 'acquaintances',
             'act-ing': 'acting', 'activ-ities': 'activities', 'activa-tion': 'activation', 'activat-ing': 'activating',
             'activi-ties': 'activities', 'actu-ally': 'actually', 'addi-tion': 'addition', 'addi-tional': 'additional',
             'ade-quate': 'adequate', 'admin-NOTES': 'adminNOTES', 'admin-istration': 'administration',
             'adminis-tration': 'administration', 'administra-tion': 'administration',
             'administra-tor': 'administrator', 'admis-sion': 'admission', 'admit-ted': 'admitted',
             'advis-ing': 'advising', 'aero-nautical': 'aeronautical', 'afflu-ent': 'affluent',
             'after-action': 'afteraction', 'after-math': 'aftermath', 'after-noon': 'afternoon',
             'agen-cies': 'agencies', 'agencies.Cer-tainly': 'agencies. Certainly', 'agree-ments': 'agreements',
             'air-borne.The': 'airborne. The', 'air-craft': 'aircraft', 'air-line': 'airline',
             'air-line.Again': 'airline.Again', 'air-lines': 'airlines', 'air-plane': 'airplane',
             'air-ports': 'airports', 'aircraft.Accord-ing': 'aircraft. According', 'al-Rahman': 'alRahman',
             'all-out': 'allout', 'all-purpose': 'allpurpose', 'all-source': 'allsource', 'allo-cating': 'allocating',
             'alti-tude': 'altitude', 'ambigui-ties': 'ambiguities', 'ana-lysts': 'analysts', 'ana-lytic': 'analytic',
             'ana-lyze': 'analyze', 'ana-lyzed': 'analyzed', 'analy-sis': 'analysis', 'analyti-cal': 'analytical',
             'announce-ment': 'announcement', 'announce-ments': 'announcements', 'antiair-craft': 'antiaircraft',
             'any-thing': 'anything', 'apart-ment.Witnesses': 'apartment. Witnesses', 'apart-ments': 'apartments',
             'apartment.Post-9/11': 'apartment. Post-9/11', 'appar-ent': 'apparent', 'appar-ently': 'apparently',
             'appear-ing': 'appearing', 'appli-cation': 'application', 'appli-cations': 'applications',
             'applica-tion': 'application', 'appoint-ing': 'appointing', 'appre-ciation': 'appreciation',
             'appreci-ated': 'appreciated', 'appro-priate': 'appropriate', 'appro-priately': 'appropriately',
             'approach-ing': 'approaching', 'appropria-tions': 'appropriations', 'approx-imately': 'approximately',
             'approxi-mately': 'approximately', 'architec-ture': 'architecture', 'artic-ulate': 'articulate',
             'ask-ing': 'asking', 'aspir-ing': 'aspiring', 'assas-sinating': 'assassinating',
             'assas-sination': 'assassination', 'assassina-tion': 'assassination', 'assem-bled': 'assembled',
             'assess-ing': 'assessing', 'assess-ment': 'assessment', 'assess-ments': 'assessments',
             'assign-ment': 'assignment', 'assim-ilate': 'assimilate', 'assis-tance': 'assistance',
             'asso-ciate': 'associate', 'asso-ciated': 'associated', 'asso-ciates': 'associates',
             'associ-ate': 'associate', 'associ-ates': 'associates', 'assur-ance': 'assurance', 'asy-lum': 'asylum',
             'athttp://english.daralhayat.com/Spec/02-2004': 'at http://english.daralhayat.com/Spec/02-2004',
             'attach-ment': 'attachment', 'attack-ers': 'attackers', 'attacks.More-over': 'attacks. Moreover',
             'atten-dants': 'attendants', 'atten-tion': 'attention', 'attrac-tive': 'attractive',
             'author-ities': 'authorities', 'author-ity': 'authority', 'authori-ties': 'authorities',
             'authoriz-ing': 'authorizing', 'authoriza-tion': 'authorization', 'avail-able': 'available',
             'aver-ages': 'averages', 'avi-ation': 'aviation', 'avia-tion': 'aviation', 'await-ing': 'awaiting',
             'back-ground': 'background', 'back-logs': 'backlogs', 'bal-ance': 'balance', 'bat-tle': 'battle',
             'begin-ning': 'beginning', 'behav-ior': 'behavior', 'believ-ers': 'believers', 'bet-ter': 'better',
             'bil-lion': 'billion', 'bil-lions': 'billions', 'bio-logical': 'biological', 'bio-metric': 'biometric',
             'biolog-ical': 'biological', 'biomet-ric': 'biometric', 'block-ing': 'blocking', 'board-ing': 'boarding',
             'boast-ing': 'boasting', 'bod-ies': 'bodies', 'bomb-ing': 'bombing', 'bomb-ings': 'bombings',
             'bomb-mak-ing': 'bomb-making', 'bor-der': 'border', 'bor-der.Upon': 'border. Upon',
             'bound-aries': 'boundaries', 'break-fast': 'breakfast', 'break-ing': 'breaking', 'brief-ing': 'briefing',
             'brief-ings': 'briefings', 'broad-cast': 'broadcast', 'broth-ers': 'brothers', 'budg-ets': 'budgets',
             'build-ing': 'building', 'build-ings': 'buildings', 'bun-galow': 'bungalow', 'cab-inet': 'cabinet',
             'cabi-net': 'cabinet', 'cam-paign': 'campaign', 'camera-man': 'cameraman', 'can-celled': 'cancelled',
             'candi-date': 'candidate', 'cap-tors': 'captors', 'cap-ture': 'capture', 'cap-tured': 'captured',
             'cap-turing': 'capturing', 'capa-bilities': 'capabilities', 'capa-bility': 'capability',
             'capa-ble': 'capable', 'capabil-ities': 'capabilities', 'capabili-ties': 'capabilities',
             'car-ried': 'carried', 'car-rier': 'carrier', 'car-rying': 'carrying',
             'career-enhanc-ing': 'career-enhancing', 'casu-alties': 'casualties',
             'casualties.Twenty-three': 'casualties. Twenty-three', 'cata-strophic': 'catastrophic',
             'cau-tion': 'caution', 'caus-ing': 'causing', 'celebra-tion': 'celebration', 'cen-ter': 'center',
             'cen-ters': 'centers', 'cen-tral': 'central', 'cen-tralization': 'centralization', 'cen-tury': 'century',
             'cer-tain': 'certain', 'cer-tainly': 'certainly', 'chair-man': 'chairman', 'chal-lenges': 'challenges',
             'champi-oned': 'championed', 'chan-nel': 'channel', 'chan-nels': 'channels', 'chap-ter': 'chapter',
             'char-acter': 'character', 'char-acterized': 'characterized', 'char-itable': 'charitable',
             'char-ities': 'charities', 'character-ization': 'characterization', 'characteriz-ing': 'characterizing',
             'check-ing': 'checking', 'check-points': 'checkpoints', 'chem-ical': 'chemical', 'chil-dren': 'children',
             'cir-cle': 'circle', 'cir-cling': 'circling', 'cir-culated': 'circulated',
             'cir-cumstances': 'circumstances', 'circu-lars': 'circulars', 'circu-lated': 'circulated',
             'circum-spect': 'circumspect', 'circumstan-tial': 'circumstantial', 'cit-ing': 'citing',
             'cit-izen': 'citizen', 'cit-izens': 'citizens', 'citi-zens': 'citizens', 'citi-zenship': 'citizenship',
             'civ-ilization': 'civilization', 'civ-ilized': 'civilized', 'civil-ian': 'civilian',
             'civil-ians': 'civilians', 'clan-destine': 'clandestine', 'cleans-ing': 'cleansing',
             'climb-ing': 'climbing', 'clos-est': 'closest', 'coali-tion': 'coalition', 'cock-pit': 'cockpit',
             'col-laboration': 'collaboration', 'col-laborators': 'collaborators', 'col-lapse': 'collapse',
             'col-lapsed': 'collapsed', 'col-league': 'colleague', 'col-leagues': 'colleagues',
             'col-leagues.Though': 'colleagues. Though', 'col-lect': 'collect', 'col-lected': 'collected',
             'col-lection': 'collection', 'col-lege': 'college', 'collapsed.How-ever': 'collapsed. However',
             'collec-tion': 'collection', 'com-bat': 'combat', 'com-bination': 'combination', 'com-bined': 'combined',
             'com-ing': 'coming', 'com-mand': 'command', 'com-mand.In': 'command.In', 'com-mander': 'commander',
             'com-manders': 'commanders', 'com-mands': 'commands', 'com-merce': 'commerce',
             'com-mercially': 'commercially', 'com-mitments': 'commitments', 'com-mitted': 'committed',
             'com-mittee': 'committee', 'com-monly': 'commonly', 'com-municate': 'communicate',
             'com-municated': 'communicated', 'com-munication': 'communication',
             'com-munication.The': 'communication. The', 'com-munications': 'communications', 'com-munity': 'community',
             'com-panies': 'companies', 'com-pany': 'company', 'com-pared': 'compared', 'com-plained': 'complained',
             'com-plement': 'complement', 'com-plete': 'complete', 'com-pleted': 'completed',
             'com-pletion': 'completion', 'com-plex': 'complex', 'com-plex.Officers': 'complex. Officers',
             'com-plicity': 'complicity', 'com-pound': 'compound', 'com-puter': 'computer',
             'com-puterized': 'computerized', 'combat-ant': 'combatant', 'combat-ing': 'combating',
             'comfort-ably': 'comfortably', 'command-ers': 'commanders', 'commence-ment': 'commencement',
             'commer-cial': 'commercial', 'commit-ted': 'committed', 'commit-tee': 'committee',
             'commit-tees': 'committees', 'commu-nication': 'communication', 'commu-nity': 'community',
             'communi-cate': 'communicate', 'communi-cated': 'communicated', 'communi-cation': 'communication',
             'communica-tion': 'communication', 'communica-tions': 'communications', 'communicat-ing': 'communicating',
             'compa-nies': 'companies', 'compan-ion': 'companion', 'compartmenta-tion': 'compartmentation',
             'compla-cency': 'complacency', 'compre-hensive': 'comprehensive', 'con-ceal': 'conceal',
             'con-centrate': 'concentrate', 'con-cern': 'concern', 'con-cerned': 'concerned',
             'con-cerning': 'concerning', 'con-cerns': 'concerns', 'con-cluded': 'concluded',
             'con-clusive': 'conclusive', 'con-course': 'concourse', 'con-cur': 'concur', 'con-ditions': 'conditions',
             'con-duct': 'conduct', 'con-ducted': 'conducted', 'con-duit': 'conduit', 'con-federated': 'confederated',
             'con-federation': 'confederation', 'con-ference': 'conference', 'con-firm': 'confirm',
             'con-firmed': 'confirmed', 'con-flict': 'conflict', 'con-flicts': 'conflicts', 'con-fusion': 'confusion',
             'con-gregate': 'congregate', 'con-gressional': 'congressional', 'con-nect': 'connect',
             'con-nected': 'connected', 'con-necting': 'connecting', 'con-nection': 'connection',
             'con-nections': 'connections', 'con-sequence': 'consequence', 'con-sider': 'consider',
             'con-sideration': 'consideration', 'con-sidered': 'considered', 'con-sidering': 'considering',
             'con-sisted': 'consisted', 'con-sistent': 'consistent', 'con-sistently': 'consistently',
             'con-solidate': 'consolidate', 'con-stitutionality': 'constitutionality', 'con-structed': 'constructed',
             'con-structive': 'constructive', 'con-sular': 'consular', 'con-suming': 'consuming', 'con-tact': 'contact',
             'con-tacts': 'contacts', 'con-tacts.They': 'contacts. They', 'con-tained': 'contained',
             'con-taining': 'containing', 'con-templated': 'contemplated', 'con-tenders': 'contenders',
             'con-text': 'context', 'con-tinue': 'continue', 'con-tinued': 'continued', 'con-tinuing': 'continuing',
             'con-trast': 'contrast', 'con-trol': 'control', 'con-trolled': 'controlled', 'con-troller': 'controller',
             'con-trollers': 'controllers', 'con-trols': 'controls', 'con-troversial': 'controversial',
             'con-versation': 'conversation', 'con-verted': 'converted', 'con-vinced': 'convinced',
             'concen-trate': 'concentrate', 'concen-trated': 'concentrated', 'concen-trates': 'concentrates',
             'concern-ing': 'concerning', 'concerns.Mem-bers': 'concerns. Members', 'conclu-sion': 'conclusion',
             'concur-rence': 'concurrence', 'conduct.Thu-mairy': 'conduct. Thumairy', 'confer-ees': 'conferees',
             'confer-ence': 'conference', 'confiden-tial': 'confidential', 'connec-tions': 'connections',
             'conse-quence': 'consequence', 'conse-quently': 'consequently', 'consid-erable': 'considerable',
             'consid-erably': 'considerably', 'consider-able': 'considerable', 'conspic-uous': 'conspicuous',
             'construc-tion': 'construction', 'contend-ing': 'contending', 'contin-gency': 'contingency',
             'contin-ued': 'continued', 'contin-ues': 'continues', 'control-ling': 'controlling',
             'conver-sations': 'conversations', 'conversa-tion': 'conversation', 'coop-erate': 'cooperate',
             'coop-erating': 'cooperating', 'coop-eration': 'cooperation', 'cooper-ating': 'cooperating',
             'cooper-ation': 'cooperation', 'coor-dinate': 'coordinate', 'coor-dinated': 'coordinated',
             'coor-dinating': 'coordinating', 'coor-dinator': 'coordinator', 'coordi-nate': 'coordinate',
             'coordi-nated': 'coordinated', 'coordi-nating': 'coordinating', 'coordina-tor': 'coordinator',
             'cop-per': 'copper', 'coun-sel': 'counsel', 'coun-seled': 'counseled', 'coun-terattack': 'counterattack',
             'coun-terparts': 'counterparts', 'coun-terterrorism': 'counterterrorism',
             'coun-terterrorism.We': 'counterterrorism. We', 'coun-tries': 'countries', 'coun-try': 'country',
             'coun-try.Although': 'country. Although', 'counter-attack': 'counterattack', 'counter-feit': 'counterfeit',
             'counter-terrorism': 'counterterrorism', 'counterproduc-tive': 'counterproductive',
             'countert-errorism': 'counterterrorism', 'counterter-rorism': 'counterterrorism',
             'counterterror-ism': 'counterterrorism', 'counterterrorism.Inte-grating': 'counterterrorism. Integrating',
             'cov-erage': 'coverage', 'cover-age.Clarke': 'coverage. Clarke', 'cre-ate': 'create',
             'cre-ated': 'created', 'cred-ible': 'credible', 'credi-ble': 'credible', 'crim-inal': 'criminal',
             'crim-inals': 'criminals', 'crimi-nal': 'criminal', 'crit-icized': 'criticized',
             'crite-ria.See': 'criteria. See', 'cross-country': 'crosscountry', 'cru-cial': 'crucial',
             'cul-tural': 'cultural', 'cul-ture': 'culture', 'cur-rency': 'currency', 'cur-rent': 'current',
             'cur-rently': 'currently', 'cus-tody': 'custody', 'cus-tody.The': 'custody. The', 'cut-ting': 'cutting',
             'cybersecu-rity': 'cybersecurity', 'dam-age': 'damage', 'dan-ger': 'danger', 'dan-gerous': 'dangerous',
             'danger-ous': 'dangerous', 'data-base': 'database', 'data-bases': 'databases', 'daugh-ter': 'daughter',
             'deal-ing': 'dealing', 'deci-phered': 'deciphered', 'deci-sion': 'decision',
             'deci-sionmaking': 'decision-making', 'deci-sions': 'decisions', 'decisionmak-ing': 'decisionmaking',
             'ded-icated': 'dedicated', 'defend-ing': 'defending', 'defer-ring': 'deferring',
             'del-egation': 'delegation', 'dele-gates': 'delegates', 'delib-erate': 'deliberate',
             'deliv-ering': 'delivering', 'dem-olition': 'demolition', 'demo-cratic': 'democratic',
             'demon-strated': 'demonstrated', 'denial.Accord-ing': 'denial. According', 'depar-ture': 'departure',
             'depart-ment': 'department', 'depart-mental': 'departmental', 'depart-ments': 'departments',
             'deploy-ment': 'deployment', 'des-ignate': 'designate', 'des-ignated': 'designated',
             'descrip-tion': 'description', 'desper-ate': 'desperate', 'desper-ately': 'desperately',
             'despi-cable': 'despicable', 'detec-tion': 'detection', 'detec-tors': 'detectors',
             'deter-mination': 'determination', 'deter-mine': 'determine', 'deter-mined': 'determined',
             'deter-mining': 'determining', 'deter-rence': 'deterrence', 'determi-nation': 'determination',
             'deto-nated': 'detonated', 'devel-oped': 'developed', 'devel-oping': 'developing',
             'devel-opments': 'developments', 'develop-ing': 'developing', 'dia-logue': 'dialogue',
             'dia-monds': 'diamonds', 'died.Twenty-six': 'died. Twenty-six', 'dif-ferent': 'different',
             'dif-ficult': 'difficult', 'differ-ences.Binalshibh': 'differences. Binalshibh', 'differ-ent': 'different',
             'diffi-cult': 'difficult', 'diffi-culty': 'difficulty', 'dig-itized': 'digitized', 'dili-gent': 'diligent',
             'dimin-ished': 'diminished', 'diplo-macy': 'diplomacy', 'diplo-matic': 'diplomatic',
             'direc-tion': 'direction', 'direc-tive': 'directive', 'direc-tor': 'director', 'direct-ing': 'directing',
             'dis-agree': 'disagree', 'dis-closed': 'disclosed', 'dis-continue': 'discontinue',
             'dis-counted': 'discounted', 'dis-cover': 'discover', 'dis-cretion': 'discretion', 'dis-cuss': 'discuss',
             'dis-cussed': 'discussed', 'dis-cussion': 'discussion', 'dis-grace': 'disgrace', 'dis-patch': 'dispatch',
             'dis-patcher': 'dispatcher', 'dis-patchers': 'dispatchers', 'dis-putes': 'disputes', 'dis-rupt': 'disrupt',
             'dis-ruptions': 'disruptions', 'dis-sembled': 'dissembled', 'dis-seminates': 'disseminates',
             'dis-tant': 'distant', 'dis-tinction': 'distinction', 'dis-tinctly': 'distinctly',
             'dis-tribute': 'distribute', 'dis-tribution': 'distribution', 'disagree-ment': 'disagreement',
             'disap-pointing': 'disappointing', 'disclo-sure': 'disclosure', 'discov-ered': 'discovered',
             'discus-sion': 'discussion', 'disori-ented': 'disoriented', 'disposi-tion': 'disposition',
             'disrup-tion': 'disruption', 'dissemi-nated': 'disseminated', 'dissi-dents.The': 'dissidents. The',
             'distrib-uted': 'distributed', 'distribu-tion': 'distribution', 'divi-dend': 'dividend',
             'divi-sion': 'division', 'doc-umentaries': 'documentaries', 'doc-uments': 'documents',
             'doctor-ing': 'doctoring', 'docu-ment': 'document', 'docu-ments': 'documents',
             'docu-ments.Pub.L.No': 'documents. Pub.L.No', 'docu-ments.The': 'documents. The',
             'documenta-tion': 'documentation', 'dom-inant': 'dominant', 'domes-tic': 'domestic',
             'dona-tions.Al': 'donations. Al', 'dor-mitory': 'dormitory', 'dou-bled': 'doubled',
             'dove-tail': 'dovetail', 'dra-matic': 'dramatic', 'dra-matically': 'dramatically', 'dress-ing': 'dressing',
             'dupli-cation': 'duplication', 'dur-ing': 'during', 'ear-lier': 'earlier', 'ear-lier.The': 'earlier. The',
             'eas-ier': 'easier', 'eco-nomic': 'economic', 'econ-omy': 'economy', 'economi-cally': 'economically',
             'edu-cation': 'education', 'edu-cational': 'educational', 'effec-tive': 'effective',
             'effec-tiveness': 'effectiveness', 'effective-ness': 'effectiveness', 'effi-ciency': 'efficiency',
             'elab-orate': 'elaborate', 'ele-ment': 'element', 'ele-ments': 'elements', 'ele-vator': 'elevator',
             'ele-vators': 'elevators', 'elec-tricity': 'electricity', 'elec-tronic': 'electronic',
             'electri-cal': 'electrical', 'electron-ics': 'electronics', 'eleva-tors': 'elevators',
             'elim-inate': 'eliminate', 'elimi-nate': 'eliminate', 'else-where': 'elsewhere', 'em-ployees': 'employees',
             'emer-gencies': 'emergencies', 'emer-gency': 'emergency', 'empha-sis': 'emphasis',
             'empha-size': 'emphasize', 'empha-sized': 'emphasized', 'emphasiz-ing': 'emphasizing',
             'empty-handed': 'emptyhanded', 'encoun-tered': 'encountered', 'encour-aged': 'encouraged',
             'encourag-ing': 'encouraging', 'endors-ing': 'endorsing', 'enforce-ment': 'enforcement',
             'enor-mous': 'enormous', 'enough.Team-work': 'enough. Teamwork', 'enter-prise': 'enterprise',
             'enti-tled': 'entitled', 'entt-bomb': 'enttbomb', 'environ-ment': 'environment',
             'equiv-ocating': 'equivocating', 'estab-lish': 'establish', 'estab-lished': 'established',
             'esti-mate': 'estimate', 'evac-uate': 'evacuate', 'evac-uate.The': 'evacuate. The',
             'evac-uation': 'evacuation', 'evacu-ated': 'evacuated', 'evacu-ation': 'evacuation',
             'evacua-tion': 'evacuation', 'evalu-ated': 'evaluated', 'even-tually': 'eventually',
             'eventu-ally': 'eventually', 'every-body': 'everybody', 'every-one': 'everyone', 'evi-dence': 'evidence',
             'evi-dence.The': 'evidence. The', 'evi-denced': 'evidenced', 'evi-dent': 'evident',
             'evo-lution': 'evolution', 'exac-erbate': 'exacerbate', 'exacer-bate': 'exacerbate',
             'exacer-bating': 'exacerbating', 'exam-ined': 'examined', 'exam-ines': 'examines',
             'exam-ining': 'examining', 'exam-ple': 'example', 'examin-ing': 'examining', 'excep-tion': 'exception',
             'excep-tional': 'exceptional', 'exclu-sively': 'exclusively', 'exec-utive': 'executive',
             'execu-tive': 'executive', 'exer-cise': 'exercise', 'exist-ing': 'existing', 'expe-rienced': 'experienced',
             'expen-sive': 'expensive', 'experi-ence': 'experience', 'explo-sives': 'explosives',
             'explosives-laden': 'explosivesladen', 'expul-sion': 'expulsion', 'extrem-ist': 'extremist',
             'extrem-ists': 'extremists', 'eye-witness': 'eyewitness', 'fac-tor': 'factor', 'facil-itate': 'facilitate',
             'facil-ity': 'facility', 'facili-tator': 'facilitator', 'facili-ties': 'facilities', 'fail-ure': 'failure',
             'fal-sified': 'falsified', 'fam-ilies': 'families', 'fam-ily': 'family', 'familiar-ity': 'familiarity',
             'far-ing': 'faring', 'fash-ionable': 'fashionable', 'fatal-ities': 'fatalities', 'fea-sible': 'feasible',
             'feasi-bility': 'feasibility', 'fed-eral': 'federal', 'fel-low': 'fellow', 'fig-ure': 'figure',
             'fig-ures': 'figures', 'fight-ing': 'fighting', 'figur-ing': 'figuring', 'finan-cial': 'financial',
             'find-ing': 'finding', 'finger-prints': 'fingerprints', 'fire-ball': 'fireball',
             'fire-fighter': 'firefighter', 'fire-fighters': 'firefighters', 'fire-houses': 'firehouses',
             'firefight-ers': 'firefighters', 'firefight-ing': 'fire-fighting', 'first-class': 'firstclass',
             'fit-ness': 'fitness', 'flow-ing': 'flowing', 'flow-ing.To': 'flowing. To', 'flu-ency': 'fluency',
             'fly-ing': 'flying', 'focus-ing': 'focusing', 'fol-lowed': 'followed', 'fol-lowers': 'followers',
             'fol-lowing': 'following', 'follow-ers': 'followers', 'follow-ing': 'following', 'for-eign': 'foreign',
             'for-ever': 'forever', 'for-gotten': 'forgotten', 'for-mal': 'formal', 'for-mally': 'formally',
             'for-ward': 'forward', 'formu-lated': 'formulated', 'frac-tion': 'fraction', 'frac-tious': 'fractious',
             'fragmen-tary': 'fragmentary', 'fraud-ulent': 'fraudulent', 'fre-quency': 'frequency',
             'fre-quent': 'frequent', 'fre-quently': 'frequently', 'frequen-cies': 'frequencies',
             'friend-ship': 'friendship', 'frus-trated': 'frustrated', 'frus-trations': 'frustrations',
             'frustra-tion': 'frustration', 'fugi-tives': 'fugitives', 'fun-damentalism': 'fundamentalism',
             'func-tion': 'function', 'func-tions': 'functions', 'fund-ing': 'funding', 'fund-raising': 'fundraising',
             'fundamental-ist': 'fundamentalist', 'fur-ther': 'further', 'furnish-ings': 'furnishings',
             'gath-ered': 'gathered', 'gen-erally': 'generally', 'gen-eration': 'generation',
             'gen-erously': 'generously', 'gener-ally': 'generally', 'get-ting': 'getting', 'giv-ing': 'giving',
             'glob-alization.Terrorism': 'globalization. Terrorism', 'gov-erned': 'governed',
             'gov-ernment': 'government', 'gov-ernment.The': 'government. The', 'gov-ernmental': 'governmental',
             'gov-ernments': 'governments', 'gover-nance': 'governance', 'govern-ing': 'governing',
             'govern-ment': 'government', 'govern-ment.This': 'government. This',
             'govern-ment.While': 'government. While', 'govern-ments': 'governments', 'grad-uate': 'graduate',
             'griev-ances': 'grievances', 'ground.Thought-ful': 'ground.Thoughtful', 'grow-ing': 'growing',
             'guid-ance': 'guidance', 'guide-lines': 'guidelines', 'gun-man': 'gunman', 'han-dle': 'handle',
             'han-dled': 'handled', 'han-dling': 'handling', 'hand-ful': 'handful', 'hand-icapping': 'handicapping',
             'hap-pened': 'happened', 'har-bor': 'harbor', 'hav-HOW': 'havHOW', 'hav-ing': 'having',
             'haz-ardous': 'hazardous', 'head-ing': 'heading', 'head-quarters': 'headquarters',
             'headquar-tered': 'headquartered', 'headquar-ters': 'headquarters', 'hear-ings': 'hearings',
             'hel-icopter': 'helicopter', 'hel-icopters': 'helicopters', 'hel-iport': 'heliport',
             'heli-copter': 'helicopter', 'heli-copters': 'helicopters', 'help.Bay-oumi': 'help.Bayoumi',
             'hijack-ers': 'hijackers', 'hijack-ing': 'hijacking', 'hijack-ings': 'hijackings', 'him-self': 'himself',
             'hit-ting': 'hitting', 'hold-ing': 'holding', 'home-land': 'homeland', 'hon-ored': 'honored',
             'hop-ing': 'hoping', 'house-mate': 'housemate', 'how-ever': 'however', 'hub-and-spoke': 'hub-andspoke',
             'hun-dred': 'hundred', 'hun-dreds': 'hundreds', 'hunt-ing': 'hunting', 'ide-ologies': 'ideologies',
             'iden-tified': 'identified', 'iden-tifier': 'identifier', 'iden-tify': 'identify',
             'identi-fication': 'identification', 'identi-fied': 'identified',
             'identifi-cation.DCI': 'identification. DCI', 'identifi-cation.The': 'identification. The',
             'ideo-logical': 'ideological', 'ille-gally': 'illegally', 'imag-ine': 'imagine', 'imme-diate': 'immediate',
             'imme-diately': 'immediately', 'imme-diately.While': 'immediately. While', 'immedi-ately': 'immediately',
             'immi-gration': 'immigration', 'immigra-tion': 'immigration', 'impass-able': 'impassable',
             'imple-mentation': 'implementation', 'imple-mented': 'implemented', 'implement-ing': 'implementing',
             'impli-cations': 'implications', 'implic-itly': 'implicitly', 'impor-tant': 'important',
             'impos-sible': 'impossible', 'impre-cise': 'imprecise', 'impro-vised': 'improvised',
             'inabil-ity': 'inability', 'inac-curate': 'inaccurate', 'inad-equately': 'inadequately',
             'inaugu-ration': 'inauguration', 'inci-dent': 'incident', 'inci-dent.At': 'incident.At',
             'includ-ing': 'including', 'incom-plete': 'incomplete', 'inconclu-sive': 'inconclusive',
             'incorpo-rating': 'incorporating', 'increas-ing': 'increasing', 'increas-ingly': 'increasingly',
             'incremen-tal': 'incremental', 'inde-pendently': 'independently', 'indefi-nitely': 'indefinitely',
             'indepen-dent': 'independent', 'indi-cates': 'indicates', 'indi-cating': 'indicating',
             'indi-cation': 'indication', 'indi-cators': 'indicators', 'indi-vidual': 'individual',
             'indi-viduals': 'individuals', 'indica-tion': 'indication', 'indict-ing': 'indicting',
             'indict-ment': 'indictment', 'indiscrimi-nate': 'indiscriminate', 'individ-ual': 'individual',
             'individ-uals': 'individuals', 'individu-als': 'individuals', 'indoctri-nate': 'indoctrinate',
             'ineffec-tual': 'ineffectual', 'iner-tia': 'inertia', 'inexperi-ence': 'inexperience',
             'influ-ence': 'influence', 'infor-196': 'infor196', 'infor-mation': 'information',
             'infor-mation.That': 'information. That', 'informa-tion': 'information',
             'infra-structure': 'infrastructure', 'infrastruc-ture': 'infrastructure', 'ini-tial': 'initial',
             'ini-tially': 'initially', 'ini-tiative': 'initiative', 'ini-tiatives': 'initiatives',
             'inno-cent': 'innocent', 'inspec-tion': 'inspection', 'instal-lations.The': 'installations. The',
             'insti-gation': 'instigation', 'insti-tutional': 'institutional', 'instruc-tions': 'instructions',
             'instruc-tor': 'instructor', 'insur-gencies': 'insurgencies', 'inte-grate': 'integrate',
             'inte-grated': 'integrated', 'inte-grating': 'integrating', 'inte-gration': 'integration',
             'intel-ligence': 'intelligence', 'intel-ligence.This': 'intelligence. This',
             'intelli-gence': 'intelligence', 'intelli-gence.The': 'intelligence. The', 'intend-ing': 'intending',
             'inter-agency': 'interagency', 'inter-cept': 'intercept', 'inter-cepts': 'intercepts',
             'inter-est': 'interest', 'inter-ested': 'interested', 'inter-ests': 'interests',
             'inter-mediaries': 'intermediaries', 'inter-mediary': 'intermediary', 'inter-nal': 'internal',
             'inter-national': 'international', 'inter-pretation': 'interpretation', 'inter-rogation': 'interrogation',
             'inter-rogation.Contrary': 'interrogation. Contrary', 'inter-rogations': 'interrogations',
             'inter-vened': 'intervened', 'inter-view': 'interview', 'inter-viewed': 'interviewed',
             'inter-views': 'interviews', 'interna-tional': 'international', 'interro-gation': 'interrogation',
             'interro-gations': 'interrogations', 'interroga-tion': 'interrogation',
             'interroga-tions': 'interrogations', 'interven-tion': 'intervention', 'intro-duced': 'introduced',
             'intu-itive': 'intuitive', 'invad-ing': 'invading', 'inves-tigate': 'investigate',
             'inves-tigated': 'investigated', 'inves-tigation': 'investigation', 'inves-tigations': 'investigations',
             'inves-tigative': 'investigative', 'investi-gation': 'investigation', 'investiga-tion': 'investigation',
             'investiga-tion.The': 'investigation.The', 'investiga-tions': 'investigations',
             'investiga-tive': 'investigative', 'investigat-ing': 'investigating', 'invi-tation': 'invitation',
             'involve-ment': 'involvement', 'is-ill': 'isill', 'ital-icized': 'italicized',
             'juris-diction': 'jurisdiction', 'jut-ted': 'jutted', 'knowl-edge': 'knowledge', 'lad-der': 'ladder',
             'lan-guage': 'language', 'land-ing': 'landing', 'land-ings': 'landings', 'last-minute': 'lastminute',
             'launder-ers': 'launderers', 'launder-ing': 'laundering', 'law-fulness': 'lawfulness',
             'lay-ered': 'layered', 'lead-ers': 'leaders', 'lead-ership': 'leadership', 'lead-ing': 'leading',
             'leader-ship': 'leadership', 'learn-ing': 'learning', 'leav-ing': 'leaving', 'lec-ture': 'lecture',
             'let-ter': 'letter', 'leverag-ing': 'leveraging', 'lieu-tenant': 'lieutenant',
             'lieu-tenants': 'lieutenants', 'lim-ited': 'limited', 'lim-itless.Goals': 'limitless. Goals',
             'linked.Com-merce': 'linked. Commerce', 'liq-uid': 'liquid', 'lit-tle': 'little', 'll-So': 'llSo',
             'loca-tion': 'location', 'lock-ing': 'locking', 'logis-tical': 'logistical',
             'long-standing': 'longstanding', 'long-time': 'longtime', 'look-ing': 'looking', 'lug-gage': 'luggage',
             'magni-tude': 'magnitude', 'mail-box': 'mailbox', 'mail-boxes': 'mailboxes', 'main-tained': 'maintained',
             'main-taining': 'maintaining', 'major-ity': 'majority', 'mak-ing': 'making', 'man-agement': 'management',
             'man-ager': 'manager', 'man-agers': 'managers', 'man-date': 'mandate', 'man-dated': 'mandated',
             'man-ner': 'manner', 'man-ning': 'manning', 'man-ufactured': 'manufactured',
             'mani-festations': 'manifestations', 'manip-ulated': 'manipulated', 'mas-ter': 'master',
             'mas-terful': 'masterful', 'master-mind': 'mastermind', 'mat-ter': 'matter', 'mat-ters': 'matters',
             'mate-rial': 'material', 'mate-rials': 'materials', 'matter.Pub-lic': 'matter. Public',
             'max-imum': 'maximum', 'maxi-mum': 'maximum', 'mean-ingful': 'meaningful',
             'meas-ures.This': 'measures. This', 'mech-anisms': 'mechanisms', 'meet-ing': 'meeting',
             'meet-ings': 'meetings', 'mem-ber': 'member', 'mem-bers': 'members', 'mem-orandum': 'memorandum',
             'memo-randum': 'memorandum', 'men-tion': 'mention', 'men-tioned': 'mentioned', 'mes-sage': 'message',
             'mes-sages': 'messages', 'mes-senger': 'messenger', 'meth-ods.When': 'methods.When', 'mid-1997': 'mid1997',
             'mid-1998': 'mid1998', 'mid-1999': 'mid1999', 'mid-November': 'midNovember', 'mid-western': 'midwestern',
             'mil-itary': 'military', 'mil-lennial': 'millennial', 'mili-tary': 'military', 'millen-nium': 'millennium',
             'min-imum': 'minimum', 'min-istry': 'ministry', 'min-utes': 'minutes', 'mini-mization': 'minimization',
             'mini-mize': 'minimize', 'mis-sile': 'missile', 'mis-siles': 'missiles',
             'mis-siles.Though': 'missiles. Though', 'mis-sion': 'mission', 'mis-sion.This': 'mission. This',
             'mis-takes': 'mistakes', 'missile-smuggling': 'missilesmuggling',
             'mission.Binal-shibh': 'mission. Binalshibh', 'mit-igating': 'mitigating', 'mix-ture': 'mixture',
             'mobi-lizing': 'mobilizing', 'mod-ern': 'modern', 'mod-ifications': 'modifications',
             'moder-ate': 'moderate', 'more-over': 'moreover', 'morn-ing': 'morning',
             'morn-ing.Although': 'morning. Although', 'moun-tainous': 'mountainous', 'mov-ing': 'moving',
             'move-ment': 'movement', 'mujahi-deen': 'mujahideen', 'mul-tiple': 'multiple', 'multi-plied': 'multiplied',
             'multi-year': 'multiyear', 'mus-cle': 'muscle', 'nar-cotics': 'narcotics', 'nas-cent': 'nascent',
             'nation-als': 'nationals', 'nec-essarily': 'necessarily', 'nec-essary': 'necessary',
             'neces-sary.When': 'necessary. When', 'neg-ative': 'negative', 'nei-ther': 'neither',
             'neigh-boring': 'neighboring', 'neighbor-ing': 'neighboring', 'neighbors.Amer-ica': 'neighbors. America',
             'net-work': 'network', 'net-work.An': 'network. An', 'net-works': 'networks',
             'never-theless': 'nevertheless', 'news-cast.The': 'newscast. The', 'nib-bling': 'nibbling',
             'nom-inations': 'nominations', 'non-Muslims.The': 'nonMuslims. The',
             'non-proliferation': 'nonproliferation', 'noncoopera-tion': 'noncooperation',
             'nondis-seminated': 'nondisseminated', 'nongovern-mental': 'nongovernmental', 'nonvio-lent': 'nonviolent',
             'nor-mally': 'normally', 'noth-ing': 'nothing', 'noti-fying': 'notifying', 'num-ber': 'number',
             'num-bers': 'numbers', 'numer-ical': 'numerical', 'numer-ous': 'numerous', 'objec-tion': 'objection',
             'objec-tive': 'objective', 'objec-tives': 'objectives', 'obli-gation': 'obligation',
             'obli-gations': 'obligations', 'obtain-ing': 'obtaining', 'occa-sion': 'occasion',
             'occa-sionally': 'occasionally', 'occa-sions': 'occasions', 'occu-pants': 'occupants',
             'offen-sive': 'offensive', 'offi-cer': 'officer', 'offi-cers': 'officers', 'offi-cial': 'official',
             'offi-cials': 'officials', 'offset-ting': 'offsetting', 'omi-nous': 'ominous',
             'on9/11-related': 'on 9/11-related', 'one-month': 'onemonth', 'open-ing': 'opening', 'oper-ate': 'operate',
             'oper-ated': 'operated', 'oper-ating': 'operating', 'oper-ation': 'operation',
             'oper-ation.Clarke': 'operation. Clarke', 'oper-ation.That': 'operation. That',
             'oper-ational': 'operational', 'oper-ations': 'operations', 'oper-ations.He': 'operations. He',
             'oper-ations.The': 'operations. The', 'oper-ations.With': 'operations. With', 'oper-ative': 'operative',
             'oper-atives': 'operatives', 'oper-ators': 'operators', 'opera-tion': 'operation',
             'opera-tion.He': 'operation. He', 'opera-tional': 'operational', 'opera-tions': 'operations',
             'opera-tions.As': 'operations. As', 'opera-tives': 'operatives', 'oppo-sition': 'opposition',
             'oppor-tunities': 'opportunities', 'oppor-tunity': 'opportunity', 'oppor-tunity.The': 'opportunity. The',
             'opportu-nity': 'opportunity', 'orga-nizational': 'organizational', 'organ-ization': 'organization',
             'organi-zation': 'organization', 'organiza-tion': 'organization', 'organiza-tions': 'organizations',
             'origi-nating': 'originating', 'oth-ers': 'others', 'our-selves': 'ourselves', 'out-dated': 'outdated',
             'out-lays': 'outlays', 'out-put': 'output', 'out-side': 'outside', 'out-skirts': 'outskirts',
             'out-standing': 'outstanding', 'out-weighed': 'outweighed', 'out-weighs': 'outweighs',
             'over-all': 'overall', 'over-arching': 'overarching', 'over-classifying': 'overclassifying',
             'over-lay': 'overlay', 'over-seas': 'overseas', 'over-stated': 'overstated',
             'over-throwing': 'overthrowing', 'over-weight': 'overweight', 'over-whelmed': 'overwhelmed',
             'overabun-dance': 'overabundance', 'par-ticipants': 'participants', 'par-ticular': 'particular',
             'par-ticularly': 'particularly', 'par-ties': 'parties', 'para-medics': 'paramedics',
             'paral-lel': 'parallel', 'partic-ipate': 'participate', 'partici-pate': 'participate',
             'partici-pated': 'participated', 'participa-tion': 'participation', 'particu-lar': 'particular',
             'pas-senger': 'passenger', 'pas-sengers': 'passengers', 'pass-port': 'passport', 'pass-ports': 'passports',
             'passen-ger': 'passenger', 'passen-gers': 'passengers', 'pend-ing': 'pending',
             'pene-tration': 'penetration', 'peo-ple': 'people', 'peo-ple.They': 'people. They', 'per-564': 'per564',
             'per-ceive': 'perceive', 'per-cent': 'percent', 'per-form': 'perform', 'per-formed': 'performed',
             'per-haps': 'perhaps', 'per-manent': 'permanent', 'per-mission': 'permission',
             'per-petrators': 'perpetrators', 'per-severance': 'perseverance', 'per-son': 'person',
             'per-sonal': 'personal', 'per-sonalities': 'personalities', 'per-sonally': 'personally',
             'per-sonnel': 'personnel', 'per-sons': 'persons', 'per-spective': 'perspective',
             'per-suading': 'persuading', 'per-suasive': 'persuasive', 'perform-ance': 'performance',
             'peri-odically': 'periodically', 'permis-sion': 'permission', 'permit-ted': 'permitted',
             'perpe-trators': 'perpetrators', 'perpetra-tors': 'perpetrators', 'person-ally': 'personally',
             'person-nel': 'personnel', 'perspec-tive': 'perspective', 'pharma-ceutical': 'pharmaceutical',
             'pho-tograph': 'photograph', 'pho-tographs': 'photographs', 'pho-tos': 'photos',
             'photo-graphs': 'photographs', 'photo-graphs.When': 'photographs. When', 'pick-ing': 'picking',
             'plan-ners': 'planners', 'plan-ning': 'planning', 'plan.Accomplish-ing': 'plan. Accomplishing',
             'pol-icy': 'policy', 'poli-cies': 'policies', 'policy-makers': 'policymakers',
             'policymak-ing': 'policymaking', 'polit-ical': 'political', 'popu-lar': 'popular',
             'popu-lation': 'population', 'popula-tion': 'population', 'por-tion': 'portion', 'pos-ing': 'posing',
             'pos-sess': 'possess', 'pos-sibility': 'possibility', 'pos-sible': 'possible', 'pos-sibly': 'possibly',
             'posi-tion.The': 'position. The', 'posses-sions': 'possessions', 'possi-ble': 'possible',
             'possi-bly': 'possibly', 'poten-tial': 'potential', 'poten-tially': 'potentially', 'pow-erful': 'powerful',
             'power-ful': 'powerful', 'prac-tical': 'practical', 'prac-tices': 'practices', 'pray-ing': 'praying',
             'pre-cise': 'precise', 'pre-dict': 'predict', 'pre-eminent': 'preeminent', 'pre-existing': 'preexisting',
             'pre-ferred': 'preferred', 'pre-liminary': 'preliminary', 'pre-pared': 'prepared',
             'pre-paredness': 'preparedness', 'pre-paredness.The': 'preparedness. The', 'pre-sented': 'presented',
             'pre-serve': 'preserve', 'pre-sumed': 'presumed', 'pre-vented': 'prevented', 'pre-viously': 'previously',
             'prelim-inary': 'preliminary', 'preoccupa-tion': 'preoccupation', 'prepar-ing': 'preparing',
             'prepared-ness': 'preparedness', 'prerequi-site': 'prerequisite', 'pres-ence': 'presence',
             'pres-ent': 'present', 'pres-ident': 'president', 'pres-idential': 'presidential',
             'pres-idents': 'presidents', 'pres-sure': 'pressure', 'pres-sure.At': 'pressure. At',
             'prescrib-ing': 'prescribing', 'presen-tations': 'presentations', 'presi-dent': 'president',
             'presi-dential': 'presidential', 'presiden-tial': 'presidential', 'previ-ously': 'previously',
             'pri-marily': 'primarily', 'pri-mary': 'primary', 'pri-ority': 'priority', 'pri-vacy': 'privacy',
             'pri-vate': 'private', 'primar-ily': 'primarily', 'prin-cipals': 'principals', 'princi-pal': 'principal',
             'princi-pals': 'principals', 'prior-ities': 'priorities',
             'prior-ities.Presidents': 'priorities. Presidents', 'priori-ties': 'priorities', 'pris-oners': 'prisoners',
             'prison-ers': 'prisoners', 'private-sector': 'privatesector', 'pro-cedure': 'procedure',
             'pro-cedures': 'procedures', 'pro-ceeded': 'proceeded', 'pro-ceeds': 'proceeds',
             'pro-cessing': 'processing', 'pro-cure': 'procure', 'pro-duced': 'produced', 'pro-gram': 'program',
             'pro-gram.As': 'program. As', 'pro-grams': 'programs', 'pro-mote': 'promote', 'pro-moting': 'promoting',
             'pro-nounced': 'pronounced', 'pro-posal': 'proposal', 'pro-posals': 'proposals', 'pro-posed': 'proposed',
             'pro-tect': 'protect', 'pro-tecting': 'protecting', 'pro-tection': 'protection', 'pro-vide': 'provide',
             'pro-vided': 'provided', 'pro-vided.The': 'provided. The', 'pro-viso': 'proviso',
             'prob-ability': 'probability', 'prob-ably': 'probably', 'prob-lem': 'problem',
             'prob-lematic': 'problematic', 'prob-lems': 'problems', 'proba-bility': 'probability',
             'proba-bly': 'probably', 'proce-dures': 'procedures', 'projec-tiles': 'projectiles',
             'prom-ised': 'promised', 'prom-ising': 'promising', 'propos-als': 'proposals',
             'pros-ecutors': 'prosecutors', 'prosthe-sis': 'prosthesis', 'protect-ing': 'protecting',
             'proto-cols': 'protocols', 'provoca-tion': 'provocation', 'prox-imity': 'proximity',
             'pseudo-nym': 'pseudonym', 'pub-licity.When': 'publicity. When', 'pub-licly': 'publicly',
             'pub-lished': 'published', 'pur-chase': 'purchase', 'pur-pose': 'purpose', 'pur-suant': 'pursuant',
             'pur-sue': 'pursue', 'pur-sued': 'pursued', 'pur-suing': 'pursuing', 'quad-rennial': 'quadrennial',
             'qual-ity': 'quality', 'quali-fied': 'qualified', 'qualifi-cations': 'qualifications',
             'quan-tity': 'quantity', 'ques-tion': 'question', 'ques-tions': 'questions', 'rad-icals': 'radicals',
             'rais-ing': 'raising', 'rank-ing': 'ranking', 'rat-ing': 'rating', 'rea-sons': 'reasons',
             'reac-tion': 'reaction', 'reach-ing': 'reaching', 'read-ily': 'readily', 'real-ized': 'realized',
             'real-izing': 'realizing', 'reallo-cated': 'reallocated', 'reas-cend': 'reascend',
             'rebuild-ing': 'rebuilding', 'rec-ollection': 'recollection', 'rec-ommendations': 'recommendations',
             'rec-ommended': 'recommended', 'reca-pitulated': 'recapitulated', 'receiv-ing': 'receiving',
             'recip-ient': 'recipient', 'recipi-ent': 'recipient', 'recipi-ents': 'recipients',
             'recollec-tion': 'recollection', 'recollec-tions': 'recollections', 'recom-mendations': 'recommendations',
             'recom-mended': 'recommended', 'recommen-dations': 'recommendations', 'recommend-ing': 'recommending',
             'record-ing': 'recording', 'recruit-ing': 'recruiting', 'reen-tered': 'reentered',
             'reestab-lished': 'reestablished', 'refuel-ing': 'refueling', 'refus-ing': 'refusing',
             'reg-ular': 'regular', 'reg-ularly': 'regularly', 'reg-ulated': 'regulated', 'reg-ulations': 'regulations',
             'regard-ing': 'regarding', 'regis-tration': 'registration', 'registra-tion': 'registration',
             'regu-lar': 'regular', 'regula-tions': 'regulations', 'rein-forced': 'reinforced',
             'rel-atives': 'relatives', 'rel-ished': 'relished', 'rela-tions': 'relations',
             'rela-tionship': 'relationship', 'rela-tionships': 'relationships', 'rela-tively': 'relatively',
             'relat-ing': 'relating', 'relation-ship': 'relationship', 'relation-ships': 'relationships',
             'reli-gion': 'religion', 'reli-gious': 'religious', 'reli-giously': 'religiously',
             'reluc-tance': 'reluctance', 'rely-ing': 'relying', 'remain-ing': 'remaining',
             'remained.Working-level': 'remained. Workinglevel', 'remem-bered': 'remembered', 'remem-bers': 'remembers',
             'ren-der': 'render', 'ren-dezvous': 'rendezvous', 'rendi-tion': 'rendition',
             'rep-resentative': 'representative', 'repeat-edly': 'repeatedly', 'reper-cussions': 'repercussions',
             'report-edly': 'reportedly', 'report-ing': 'reporting', 'repre-sentative': 'representative',
             'represen-tatives': 'representatives', 'representa-tive': 'representative',
             'representa-tives': 'representatives', 'repro-grammed': 'reprogrammed', 'reprogram-ming': 'reprogramming',
             'requir-ing': 'requiring', 'required.Con-gress': 'required. Congress', 'res-cue': 'rescue',
             'res-cued': 'rescued', 'res-idence': 'residence', 'res-olution': 'resolution',
             'reser-vations': 'reservations', 'resolved.Back-page': 'resolved. Back-page', 'respec-tive': 'respective',
             'respon-der': 'responder', 'respon-sibilities': 'responsibilities', 'respon-sibility': 'responsibility',
             'respon-sible': 'responsible', 'respond-ing': 'responding',
             'responders.Nev-ertheless': 'responders. Nevertheless', 'responsi-bilities': 'responsibilities',
             'responsi-bility': 'responsibility', 'restau-rants': 'restaurants', 'restric-tion': 'restriction',
             'restric-tions': 'restrictions', 'retain-ing': 'retaining', 'retali-ate': 'retaliate',
             'retalia-tion': 'retaliation', 'return-ing': 'returning', 'rev-elations': 'revelations',
             'reveal-ing': 'revealing', 'revis-ited': 'revisited', 'ripe.Acknowl-edging': 'ripe. Acknowledging',
             'room-mate': 'roommate', 'room-mates': 'roommates', 'rou-tinely': 'routinely',
             'rudimen-tary': 'rudimentary', 'safe-house': 'safehouse', 'sam-ple': 'sample', 'sanc-tioned': 'sanctioned',
             'sanc-tions': 'sanctions', 'sanc-tuary.The': 'sanctuary. The', 'sanctu-aries': 'sanctuaries',
             'satis-factory': 'satisfactory', 'say-ing': 'saying', 'sce-nario': 'scenario',
             'scenar-ios.The': 'scenarios. The', 'sched-ules': 'schedules', 'schol-ars': 'scholars',
             'schools.Accord-ing': 'schools. According', 'scram-bled': 'scrambled', 'screen-ing': 'screening',
             'sec-ond': 'second', 'sec-retary': 'secretary', 'sec-tion': 'section', 'sec-tor': 'sector',
             'sec-ular': 'secular', 'second-ary': 'secondary', 'secre-tary': 'secretary', 'secu-NOTES': 'secuNOTES',
             'secu-rity': 'security', 'seek-ing': 'seeking', 'sen-ior': 'senior', 'sen-tence': 'sentence',
             'sepa-rate': 'separate', 'sepa-rating': 'separating', 'seri-ous': 'serious', 'seri-ously': 'seriously',
             'serv-ices': 'services', 'set-tle.They': 'settle. They', 'sev-eral': 'several', 'shap-ing': 'shaping',
             'shar-ing': 'sharing', 'shoot-down': 'shootdown', 'shout-ing': 'shouting', 'sift-ing': 'sifting',
             'sig-nal': 'signal', 'sig-nificance': 'significance', 'sig-nificant': 'significant',
             'sight-ing': 'sighting', 'signif-icant': 'significant', 'signifi-cance': 'significance',
             'signifi-cant': 'significant', 'sil-ver': 'silver', 'sim-ulator': 'simulator', 'simi-lar': 'similar',
             'similari-ties': 'similarities', 'simul-taneous': 'simultaneous', 'simul-taneously': 'simultaneously',
             'simultane-ously.Khalid': 'simultaneously. Khalid', 'single-mindedness': 'singlemindedness',
             'situa-tion': 'situation', 'situa-tion.They': 'situation. They', 'soci-eties': 'societies',
             'soft-ware': 'software', 'some-body': 'somebody', 'some-one': 'someone', 'some-time': 'sometime',
             'south-ern': 'southern', 'south-west': 'southwest', 'sover-eignty': 'sovereignty', 'spe-cial': 'special',
             'spe-cialists': 'specialists', 'spe-cific': 'specific', 'speak-ing': 'speaking',
             'spec-ulated': 'speculated', 'spec-ulating': 'speculating', 'specif-ically': 'specifically',
             'specula-tion': 'speculation', 'spir-itual': 'spiritual', 'splin-tered': 'splintered',
             'split-ting': 'splitting', 'spon-sor': 'sponsor', 'sta-bility': 'stability', 'sta-tion': 'station',
             'sta-tions': 'stations', 'sta-tus': 'status', 'stab-bings': 'stabbings', 'stair-well': 'stairwell',
             'stair-wells': 'stairwells', 'stan-dard': 'standard', 'stand-ing': 'standing', 'start-up': 'startup',
             'state-ment': 'statement', 'station.Accord-ing': 'station. According', 'stay-ing': 'staying',
             'stew-ardesses': 'stewardesses', 'sto-ries': 'stories', 'storm-ing': 'storming', 'strand-ing': 'stranding',
             'strat-egy': 'strategy', 'strate-gies': 'strategies', 'strengthen-ing': 'strengthening',
             'stress-ing': 'stressing', 'strong-willed': 'strongwilled', 'struc-tures.They': 'structures. They',
             'strug-gle': 'struggle', 'stu-dents': 'students', 'stud-ies': 'studies', 'sub-cabinet': 'subcabinet',
             'sub-ject': 'subject', 'sub-ordinates.For': 'subordinates. For', 'sub-sequent': 'subsequent',
             'sub-sequently': 'subsequently', 'sub-stance': 'substance', 'sub-stantial': 'substantial',
             'subcom-mittee': 'subcommittee', 'subse-quent': 'subsequent', 'substan-tial': 'substantial',
             'suc-cess': 'success', 'suc-cessful': 'successful', 'suc-cessor': 'successor', 'sud-denly': 'suddenly',
             'suf-fered': 'suffered', 'suf-fering': 'suffering', 'suf-ficient': 'sufficient',
             'suffi-cient': 'sufficient', 'sug-gested.Treasury': 'suggested. Treasury', 'sug-gestion': 'suggestion',
             'sug-gests': 'suggests', 'sui-cide': 'suicide', 'sum-marizing': 'summarizing', 'sum-mary': 'summary',
             'sum-mer': 'summer', 'sum-mit': 'summit', 'sup-plement': 'supplement', 'sup-plemental': 'supplemental',
             'sup-plied': 'supplied', 'sup-port': 'support', 'sup-ported': 'supported', 'sup-porters': 'supporters',
             'sup-posed': 'supposed', 'sup-posedly': 'supposedly', 'super-vise': 'supervise',
             'super-vision': 'supervision', 'support-ing': 'supporting', 'support-ive': 'supportive',
             'sur-prise': 'surprise', 'sur-rounding': 'surrounding', 'sur-veillance': 'surveillance',
             'sur-veilled': 'surveilled', 'sur-vive': 'survive', 'sus-pected': 'suspected', 'sus-tained': 'sustained',
             'suspi-cious': 'suspicious', 'sys-tem': 'system', 'sys-tem.Vice': 'system. Vice',
             'sys-tematically': 'systematically', 'sys-temic': 'systemic', 'sys-tems': 'systems',
             'tac-tical': 'tactical', 'tacti-cal': 'tactical', 'tak-ing': 'taking', 'tal-ent': 'talent',
             'tar-get': 'target', 'tar-geting': 'targeting', 'tar-gets': 'targets',
             'tar-gets.Ashcroft': 'targets. Ashcroft', 'target-ing': 'targeting', 'task-ing': 'tasking',
             'tech-nical': 'technical', 'tech-nology': 'technology', 'techni-cal': 'technical',
             'techno-logical': 'technological', 'technolo-gies': 'technologies', 'tel-evision': 'television',
             'tele-conference': 'teleconference', 'tele-phone': 'telephone',
             'telecommu-nications': 'telecommunications', 'teleconfer-ence': 'teleconference',
             'teleconfer-ence.See': 'teleconference. See', 'televi-sion': 'television', 'temper-atures': 'temperatures',
             'ten-sion': 'tension', 'ter-rorism': 'terrorism', 'ter-rorism.However': 'terrorism. However',
             'ter-rorism.Terrorists': 'terrorism. Terrorists', 'ter-rorist': 'terrorist', 'ter-rorists': 'terrorists',
             'termi-nated': 'terminated', 'terri-ble': 'terrible', 'terror-ism': 'terrorism',
             'terror-ism.The': 'terrorism. The', 'terror-ist': 'terrorist', 'terror-ists': 'terrorists',
             'terrorism.Front-page': 'terrorism. Front-page', 'testi-fied': 'testified', 'testi-mony': 'testimony',
             'the-ater': 'theater', 'the-ories': 'theories', 'them-selves': 'themselves', 'think-ing': 'thinking',
             'thou-sand': 'thousand', 'threat-ening': 'threatening', 'threaten-ing': 'threatening',
             'three-phase': 'threephase', 'time-line': 'timeline', 'toi-letries': 'toiletries', 'top-ple': 'topple',
             'track-ing': 'tracking', 'traf-fic': 'traffic', 'train-ers': 'trainers', 'train-ing': 'training',
             'tran-script': 'transcript', 'tran-scripts': 'transcripts', 'tran-siting': 'transiting',
             'trans-action.After': 'transaction. After', 'trans-actions': 'transactions', 'trans-fer': 'transfer',
             'trans-ferred': 'transferred', 'trans-fers': 'transfers', 'trans-formation': 'transformation',
             'trans-mission': 'transmission', 'trans-missions': 'transmissions', 'trans-mitted': 'transmitted',
             'trans-portation': 'transportation', 'transac-tions': 'transactions',
             'transcon-tinental': 'transcontinental', 'translat-ing': 'translating', 'transmis-sion': 'transmission',
             'transna-tional': 'transnational', 'transporta-tion': 'transportation', 'trav-eled': 'traveled',
             'trav-elers': 'travelers', 'trav-eling': 'traveling', 'travel-ers': 'travelers', 'travel-ing': 'traveling',
             'trib-als': 'tribals', 'trust-worthiness': 'trustworthiness', 'try-ing': 'trying', 'turn-ing': 'turning',
             'two-minute': 'twominute', 'ulti-mately': 'ultimately',
             'unappealing.Pro-Taliban': 'unappealing. Pro-Taliban', 'unattain-able': 'unattainable',
             'unchal-lenged': 'unchallenged', 'uncom-promising': 'uncompromising', 'unconven-tional': 'unconventional',
             'unde-niably': 'undeniably', 'under-going': 'undergoing', 'under-ground': 'underground',
             'under-lined': 'underlined', 'under-standing': 'understanding', 'under-taken': 'undertaken',
             'under-wrote': 'underwrote', 'undiscov-ered': 'undiscovered', 'unfath-omable': 'unfathomable',
             'unhap-piness': 'unhappiness', 'uni-fied': 'unified', 'unnec-essary': 'unnecessary',
             'unpre-pared': 'unprepared', 'unprece-dented': 'unprecedented', 'unquestion-ably': 'unquestionably',
             'unre-fueled': 'unrefueled', 'unre-solved': 'unresolved', 'unspeci-fied': 'unspecified',
             'up-to-date': 'upto-date', 'validat-ing': 'validating', 'vari-ety': 'variety', 'vary-ing': 'varying',
             'ver-sion': 'version', 'vet-eran': 'veteran', 'victori-ous': 'victorious', 'video-tape': 'videotape',
             'video-taped': 'videotaped', 'vig-orously': 'vigorously', 'vio-lating': 'violating',
             'vio-lence': 'violence', 'vio-lent': 'violent', 'viola-tion': 'violation', 'vir-tually': 'virtually',
             'vis-iting': 'visiting', 'visi-ble': 'visible', 'vol-ume': 'volume', 'vol-unteers': 'volunteers',
             'volun-teer': 'volunteer', 'volun-teered': 'volunteered', 'vul-nerable': 'vulnerable',
             'vulnera-ble': 'vulnerable', 'vulnerabil-ity': 'vulnerability', 'vulnerabili-ties': 'vulnerabilities',
             'war-dens': 'wardens', 'war-lord': 'warlord', 'war-lords': 'warlords', 'war-rant': 'warrant',
             'war-rants': 'warrants', 'wari-ness': 'wariness', 'watch-list': 'watchlist',
             'watch-list.These': 'watchlist. These', 'watch-listed.Had': 'watchlisted. Had', 'wel-come': 'welcome',
             'wel-ter': 'welter', 'well-organ-ized': 'well-organized', 'what-ever': 'whatever',
             'where-withal': 'wherewithal', 'wide-spread': 'widespread', 'win-dows': 'windows', 'wit-ness': 'witness',
             'wit-nesses': 'witnesses', 'wit-tingly': 'wittingly', 'with-drawn': 'withdrawn', 'with-hold': 'withhold',
             'with-out': 'without', 'woe-fully': 'woefully', 'won-dered': 'wondered', 'wor-ried': 'worried',
             'wor-thy': 'worthy', 'work-ing': 'working', 'work-place': 'workplace', 'world-wide': 'worldwide',
             'worship-pers': 'worshippers', 'writ-ten': 'written'}
    ordered_fixes = OrderedDict()
    for key in sorted(list(fixes.keys())):
        ordered_fixes[key] = fixes[key]
    # todo print these so we can just copy and paste the result as a dictionary
    print(ordered_fixes)

    examples = set()
    fix_candidates = dict()
    running_count = 0
    for index_sentence, sentence in enumerate(sentences):
        words = casual_tokenize(sentence)
        for index, word in enumerate(words):
            if word.endswith('-'):
                running_count += 1
                example = words[index - 1] + word + words[index + 1]
                fix_candidates[example] = words[index - 1] + words[index + 1]
                if example in fixes.keys():
                    print('{}: {} : {} :: {}'.format(index_sentence, running_count, example, fixes[example]))
                else:
                    print('{}: {} : {}'.format(index_sentence, running_count, example))

                examples.add(example)
    print('we found {} distinct splits'.format(len(examples)))
    print(fix_candidates)
    modified = list()
    for index_sentence, sentence in enumerate(sentences):
        words = word_tokenize(sentence)
        fixed_words = fix(words)
        modified.append(' '.join(fixed_words))
    sentences = modified

    # now we need to count words and do a frequency score for each word
    freq_dist = FreqDist()
    for sentence in sentences:
        for word in word_tokenize(sentence):
            freq_dist[word.lower()] += 1

    word_count = freq_dist.N()
    print('our frequency distribution has {} items'.format(len(freq_dist)))
    print('our word count is {}'.format(word_count))

    # now let's traverse our frequency distribution and build our token-probability map
    probabilities = {word: float(freq_dist[word]) / float(word_count) for word in freq_dist}

    # now we are ready to calculate scores for each sentence
    sentence_scores = {
        sentence: (sum([probabilities[word.lower()] for word in word_tokenize(sentence)]), index)
        for index, sentence in enumerate(sentences)}

    candidates = {key: value for key, value in sentence_scores.items() if value[0] > 3.0}

    for key, value in candidates.items():
        print('{:5.2f} {} {}'.format(value[0], value[1], key.replace('\n', ' ')))

    values = [value for value in candidates.values()]
    plt.plot(sorted(values), 'o', mfc='none')
    output_file = './output/first_cut_plot.png'
    print('writing score plot to {}'.format(output_file))
    plt.savefig(output_file)
    print('total elapsed time: {:5.2f}s'.format(time() - time_start))
